---
sidebar: sidebar 
permalink: faq-cloud-compliance.html 
keywords: faq, frequently asked questions, questions, cloud compliance, data sense 
summary: 如果您只是想要快速回答問題、這個常見問題集就能幫上忙。 
---
= 關於 BlueXP 分類的常見問題集
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果您只是想要快速回答問題、這個常見問題集就能幫上忙。



== BlueXP 分類服務

下列問題提供 BlueXP 分類的一般瞭解。



=== BlueXP 分類如何運作？

BlueXP  分類可將另一層 AI 部署在您的 BlueXP  系統和儲存系統上。然後掃描磁碟區、儲存區、資料庫及其他儲存帳戶上的資料、並為找到的資料洞見建立索引。BlueXP 分類採用人工智慧和自然語言處理、而非一般運算式和模式比對的替代解決方案。

BlueXP 分類使用 AI 提供資料的關聯式瞭解、以提供準確的偵測和分類。它是由AI驅動、因為它是專為現代資料類型和規模所設計。它也瞭解資料內容、以便提供強大、準確的探索和分類功能。

link:concept-cloud-compliance.html["深入瞭解 BlueXP 分類的運作方式"]。



=== BlueXP 分類是否有 REST API 、是否能搭配協力廠商工具使用？

是的， BlueXP  分類具有 REST API ，可用於 BlueXP  核心平台的 BlueXP  分類版本中支援的功能。請參閱。 link:api-classification.html["API 文件"]



=== BlueXP  分類是否可透過雲端市場取得？

BlueXP  分類是 BlueXP  核心功能的一部分，因此您不需要使用此服務的行銷地點。



== BlueXP 分類掃描與分析

下列問題與 BlueXP  分類掃描效能和分析有關。



=== BlueXP 分類多久掃描一次我的資料？

雖然資料的初始掃描可能需要一點時間、但後續掃描只會檢查增量變更、進而縮短系統掃描時間。BlueXP 分類會以循環方式持續掃描您的資料、一次六個儲存庫、以便快速分類所有變更的資料。

link:task-scanning-overview.html["瞭解掃描的運作方式"]。

BlueXP  分類每天只掃描一次資料庫，不會像其他資料來源一樣持續掃描資料庫。

資料掃描對儲存系統和資料的影響微乎其微。



=== 掃描效能是否有所差異？

掃描效能可能會因網路頻寬和環境中的平均檔案大小而有所不同。也可能取決於主機系統的大小特性（無論是雲端或內部部署）。如需詳細資訊、請參閱 link:concept-cloud-compliance.html["BlueXP 分類執行個體"] 和 link:task-deploy-overview.html["部署 BlueXP 分類"] 。

初次新增資料來源時，您也可以選擇僅執行「對應」（僅限對應）掃描，而非執行完整的「分類」（地圖與分類）掃描。您可以很快在資料來源上完成對應、因為它不會存取檔案來查看內部資料。link:task-scanning-overview.html["瞭解對應與分類掃描之間的差異"]。



=== 我可以使用 BlueXP 分類來搜尋我的資料嗎？

BlueXP 分類提供廣泛的搜尋功能、可讓您輕鬆搜尋所有連線來源的特定檔案或資料片段。BlueXP 分類可讓使用者比中繼資料所反映的內容更深入地搜尋。這項不受語言限制的服務也能讀取檔案、分析各種敏感資料類型、例如名稱和ID。例如、使用者可以搜尋結構化和非結構化的資料儲存區、找出可能從資料庫洩漏到使用者檔案的資料、違反企業原則。搜尋可儲存以供日後使用、並可建立原則以設定頻率搜尋結果並採取行動。

找到感興趣的檔案後、即可列出特性、包括標記、工作環境帳戶、儲存庫、檔案路徑、 類別（從分類）、檔案大小、上次修改、權限狀態、重複項目、 敏感度層級、個人資料、檔案內的敏感資料類型、擁有者、檔案類型、檔案大小、建立時間、 檔案雜湊、是否將資料指派給尋求注意的人員等。篩選條件可用於篩選出不相關的特性。

BlueXP  分類也具有角色型存取控制（ RBAC ）功能，可在擁有適當權限的情況下，允許移動或刪除檔案。如果沒有適當的權限存在、則可將工作指派給組織中擁有適當權限的人員。



== BlueXP 分類管理與隱私權

下列問題提供如何管理 BlueXP 分類和隱私權設定的資訊。



=== 如何啟用或停用 BlueXP  分類？

首先、您需要在 BlueXP 或內部部署系統中部署 BlueXP 分類執行個體。執行個體執行後、您可以從 * 組態 * 標籤或選取特定工作環境、在現有工作環境、資料庫及其他資料來源上啟用服務。link:task-getting-started-compliance.html["瞭解如何開始使用"]。


NOTE: 在資料來源上啟動 BlueXP 分類會立即進行初始掃描。掃描結果會在不久後顯示。

您可以從 BlueXP 分類組態頁面、停用 BlueXP 分類、以掃描個別工作環境、資料庫或檔案共用群組。請參閱。 link:task-managing-compliance.html["從 BlueXP 分類中移除資料來源"]

若要完全移除 BlueXP 分類執行個體、您可以從雲端供應商的入口網站或內部部署位置手動移除 BlueXP 分類執行個體。



=== 服務是否可以排除某些目錄中的掃描資料？

是的。如果您想要 BlueXP 分類排除位於特定資料來源目錄中的掃描資料、您可以將該清單提供給分類引擎。套用該變更後、 BlueXP 分類將排除指定目錄中的掃描資料。link:task-exclude-scan-paths.html["深入瞭解"]。



=== 是否掃描駐留在 ONTAP 磁碟區上的快照？

否。 BlueXP  分類不會掃描快照，因為內容與磁碟區中的內容相同。



=== 如果在您的功能區上啟用資料分層、會發生什麼情況ONTAP ？

當 BlueXP  分類掃描使用「僅對應」將冷資料分層至物件儲存的磁碟區時，會掃描本機磁碟上的所有資料，以及分層至物件儲存的冷資料。對於實作分層的非 NetApp 產品來說、也是如此。

僅對應掃描不會加熱冷資料，因為它會保持冷狀態，並保留在物件儲存區中。另一方面，如果您執行地圖和分類掃描，部分組態可能會使冷資料變熱。



== 來源系統和資料類型的類型

下列問題與可掃描的儲存設備類型及掃描的資料類型有關。



=== 在政府區域部署時、是否有任何限制？

當 Connector 部署於政府區域（ AWS GovCloud 、 Azure Gov 或 Azure DoD ）時、即稱為「受限模式」、即支援 BlueXP 分類。



=== 如果我在沒有網際網路存取的站台中安裝 BlueXP 分類、可以掃描哪些資料來源？

BlueXP 分類只能掃描內部部署站台本機資料來源的資料。目前、 BlueXP 分類可以在「私有模式」中掃描下列本機資料來源、也稱為「暗」網站：

* 內部部署ONTAP 的作業系統
* 資料庫架構
* 使用簡易儲存服務（S3）傳輸協定的物件儲存設備


請參閱。 link:concept-cloud-compliance.html["支援的工作環境和資料來源"]



=== 支援哪些檔案類型？

BlueXP 分類會掃描所有檔案、以取得類別和中繼資料的洞見、並在儀表板的檔案類型區段中顯示所有檔案類型。

當 BlueXP 分類偵測到個人識別資訊（ PII ）、或執行 DSAR 搜尋時、僅支援下列檔案格式：

`+.CSV, .DCM, .DICOM, .DOC, .DOCX, .JSON, .PDF, .PPTX, .RTF, .TXT, .XLS, .XLSX, Docs, Sheets, and Slides+`



=== BlueXP 分類擷取哪些類型的資料和中繼資料？

BlueXP 分類可讓您在資料來源上執行一般的「對應」掃描或完整的「分類」掃描。對應只提供資料的高層級總覽、而分類則提供資料的深度層級掃描。您可以很快在資料來源上完成對應、因為它不會存取檔案來查看內部資料。

* * 資料對應掃描（僅限對應掃描） * ： BlueXP  分類僅掃描中繼資料。這對整體資料管理與治理、快速專案範圍規劃、大型產業和優先順序都很有幫助。資料對應是以中繼資料為基礎、視為*快速*掃描。
+
快速掃描之後、您可以產生資料對應報告。本報告概述儲存在企業資料來源中的資料、協助您做出有關資源使用率、移轉、備份、安全性及法規遵循程序的決策。

* * 資料分類深度掃描（地圖與分類掃描） * ： BlueXP  分類掃描使用標準傳輸協定，並在整個環境中使用唯讀權限。針對敏感的業務相關資料、私有資訊及勒索軟體相關問題、會開啟並掃描選取的檔案。
+
完成完整掃描後、您可以套用許多其他 BlueXP 分類功能至資料、例如在「資料調查」頁面中檢視及精簡資料、搜尋檔案中的名稱、複製、移動及刪除來源檔案等。



BlueXP 分類會擷取中繼資料、例如：檔案名稱、權限、建立時間、上次存取和上次修改。這包括出現在「資料調查詳細資料」頁面和「資料調查報告」中的所有中繼資料。

BlueXP  分類可識別許多類型的私人資料，例如個人資訊（ PII ）和敏感個人資訊（ SPII ）。如需有關私有資料的詳細資訊，請 https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html["BlueXP 分類掃描的私有資料類別"]參閱。



=== 我可以將 BlueXP 分類資訊限制在特定使用者嗎？

是的、 BlueXP 分類與 BlueXP 完全整合。BlueXP  使用者只能根據權限查看其符合檢視資格的工作環境資訊。

此外、如果您想讓特定使用者只檢視 BlueXP  分類掃描結果、而無法管理 BlueXP  分類設定、您可以將 * 分類檢視器 * 角色（在標準模式中使用 BlueXP  時）或 * 法規遵循檢視器 * 角色（在限制模式中使用 BlueXP  時）指派給這些使用者。link:concept-cloud-compliance.html["深入瞭解"]。



=== 是否有人可以存取在我的瀏覽器和 BlueXP 分類之間傳送的私有資料？

否。您的瀏覽器與 BlueXP  分類執行個體之間傳送的私有資料會使用 TLS 1.2 來保護端點對端點加密，這表示 NetApp 和非 NetApp 方無法讀取。除非您要求並核准存取權限、否則 BlueXP 分類不會與 NetApp 分享任何資料或結果。

掃描的資料會保留在您的環境中。



=== 如何處理敏感資料？

NetApp 無法存取敏感資料、也無法在 UI 中顯示。例如、系統會遮罩敏感資料、顯示最後四個數字作為信用卡資訊。



=== 資料儲存在何處？

掃描結果會儲存在 BlueXP 分類執行個體的 Elasticsearch 中。



=== 如何存取資料？

BlueXP 分類透過 API 呼叫存取儲存在 Elasticsearch 中的資料、這需要驗證、並使用 AES-128 加密。直接存取 Elasticsearch 需要 root 存取權。



== 授權與成本

下列問題與使用 BlueXP 分類的授權和成本有關。



=== BlueXP 分類的成本是多少？

BlueXP 分類是 BlueXP 核心功能、無需付費。



== 連接器部署

下列問題與BlueXP Connector有關。



=== 什麼是Connector？

Connector是在雲端帳戶內或內部部署的運算執行個體上執行的軟體、可讓BlueXP安全地管理雲端資源。您必須部署 Connector 才能使用 BlueXP 分類。



=== 連接器需要安裝在何處？

掃描資料時， BlueXP  Connector 必須安裝在下列位置：

* 適用於 AWS 中的 Cloud Volumes ONTAP 或適用於 ONTAP 的 Amazon FSX ：連接器位於 AWS 中。
* 適用於 Azure 或 Azure NetApp Files 中的 Cloud Volumes ONTAP ： Connector 位於 Azure 中。
* 對於 GCP 中的 Cloud Volumes ONTAP ：連接器位於 GCP 中。
* 對於內部部署 ONTAP 系統：連接器為內部部署。


如果這些位置有資料，您可能需要使用 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html#when-to-use-multiple-connectors["多個連接器"^]。



=== BlueXP 分類是否需要存取認證？

BlueXP 分類本身無法擷取儲存認證。而是儲存在 BlueXP Connector 中。

BlueXP 分類使用資料層級認證、例如 CIFS 認證、在掃描前掛載共用。



=== 服務與 Connector 之間的通訊是否使用 HTTP ？

是的、 BlueXP 分類使用 HTTP 與 BlueXP Connector 通訊。



== BlueXP 分類部署

下列問題與個別的 BlueXP 分類執行個體有關。



=== BlueXP 分類支援哪些部署模式？

BlueXP可讓使用者在幾乎任何位置掃描及報告系統、包括內部部署、雲端及混合式環境。BlueXP 分類通常是使用 SaaS 模式來部署、其中服務是透過 BlueXP 介面啟用、不需要安裝硬體或軟體。即使是在這種點選即用部署模式下、資料管理也能完成、無論資料存放區是在內部部署或公有雲中。



=== BlueXP 分類需要哪種類型的執行個體或 VM ？

何時：link:task-deploy-cloud-compliance.html["部署於雲端"]

* 在 AWS 中、 BlueXP 分類是在 m6i.4xlarge 執行個體上執行、其中有 500 GiB GP2 磁碟。您可以在部署期間選取較小的執行個體類型。
* 在 Azure 中、 BlueXP 分類是在標準 D16s_v3 VM 上執行、其中含有 500 GB 磁碟。
* 在 GCP 中、 BlueXP 分類是在 n2-Standard-16 VM 上執行、其中含有 500 GiB Standard 持續性磁碟。


link:concept-cloud-compliance.html["深入瞭解 BlueXP 分類的運作方式"]。



=== 我可以在自己的主機上部署 BlueXP 分類嗎？

是的。您可以在網路或雲端上具有網際網路存取權的 Linux 主機上安裝 BlueXP 分類軟體。一切運作方式都一樣、您可以透過BlueXP繼續管理掃描組態和結果。如需系統需求和安裝詳細資料，請參閱link:task-deploy-compliance-onprem.html["在內部部署部署 BlueXP 分類"]。



=== 沒有網際網路存取的安全網站又如何？

是的、這也受到支援。您可以link:task-deploy-compliance-dark-site.html["將 BlueXP 分類部署在內部部署網站上、但該網站無法存取網際網路"]完全保護網站的安全。
