---
sidebar: sidebar 
permalink: faq-cloud-compliance.html 
keywords: faq, frequently asked questions, questions, cloud compliance, data sense 
summary: 如果您只是想要快速回答問題、這個常見問題集就能幫上忙。 
---
= 關於 BlueXP 分類的常見問題集
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果您只是想要快速回答問題、這個常見問題集就能幫上忙。



== BlueXP 分類服務

下列問題提供 BlueXP 分類的一般瞭解。



=== 什麼是 BlueXP 分類？

BlueXP 分類是一種雲端產品、採用人工智慧（ AI ）導向技術、協助您瞭解資料內容、並識別儲存系統中的敏感資料。這些系統可能是您新增至 BlueXP Canvas 的工作環境、以及 BlueXP 分類可透過網路存取的許多類型資料來源。 link:faq-cloud-compliance.html#what-sources-of-data-can-be-scanned-with-bluexp-classification["請參閱下列完整清單"]。

BlueXP 分類提供預先定義的參數（例如敏感資訊類型和類別）、以因應新的資料隱私和敏感度法規、例如 GDPR 、 CCPA 、 HIPAA 等。



=== BlueXP 分類如何運作？

BlueXP 分類可在 BlueXP 系統和儲存系統上部署另一層人工智慧。然後掃描磁碟區、儲存區、資料庫及其他儲存帳戶上的資料、並為找到的資料洞見建立索引。BlueXP 分類採用人工智慧和自然語言處理、而非一般運算式和模式比對的替代解決方案。

BlueXP 分類使用 AI 提供資料的關聯式瞭解、以提供準確的偵測和分類。它是由AI驅動、因為它是專為現代資料類型和規模所設計。它也瞭解資料內容、以便提供強大、準確的探索和分類功能。

link:concept-cloud-compliance.html["深入瞭解 BlueXP 分類的運作方式"^]。



=== BlueXP 分類的常見使用案例為何？

* 識別個人識別資訊（ PII ）。
* 根據 GDPR 、 CCPA 、 HIPAA 及其他資料隱私法規的要求、輕鬆找出特定資料並進行報告、以因應資料主題。
* 遵守新的及即將推出的資料隱私權法規。
* 遵守資料法規遵循與隱私權法規。
* 將資料從舊系統移轉至雲端。
* 遵守資料保留政策。


https://bluexp.netapp.com/netapp-cloud-data-sense["深入瞭解 BlueXP 分類的使用案例"^]。



=== BlueXP 分類架構如何？

BlueXP 分類可在雲端或內部部署單一伺服器或叢集、無論您選擇哪一種。伺服器透過標準傳輸協定連線至資料來源、並在Elasticsearch叢集中建立結果索引、該叢集也部署在相同的伺服器上。這可支援多個雲端、跨雲端、私有雲和內部部署環境。



=== 支援哪些雲端供應商？

BlueXP 分類是 BlueXP 的一部分、支援 AWS 、 Azure 和 GCP 。如此一來、您的組織便能在不同的雲端供應商之間統一化隱私權可見度。



=== BlueXP 分類是否有 REST API 、是否能搭配協力廠商工具使用？

BlueXP支援其服務的REST API功能。如果 BlueXP 不是首選的管理點、則 BlueXP 分類等服務也可以透過 REST API 使用。每個使用者動作都有REST API、可與協力廠商系統整合。



=== BlueXP 分類是否可透過市場取得？

是的、 BlueXP 和 BlueXP 分類可從 AWS 、 Azure 和 GCP 市集取得。



== BlueXP 分類掃描與分析

下列問題與 BlueXP 分類掃描效能和使用者可用的分析有關。



=== BlueXP 分類多久掃描一次我的資料？

資料經常變更、因此 BlueXP 分類會持續掃描您的資料、不會影響您的資料。雖然初次掃描資料可能需要較長時間、但後續掃描只會掃描遞增變更、如此可縮短系統掃描時間。

link:concept-cloud-compliance.html#how-scans-work["瞭解掃描的運作方式"]。

資料掃描對儲存系統和資料的影響微乎其微。不過、如果您擔心影響很小、您可以設定 BlueXP 分類來執行「慢速」掃描。 link:task-reduce-scan-speed.html["瞭解如何降低掃描速度"]。



=== 我可以使用 BlueXP 分類來搜尋我的資料嗎？

BlueXP 分類提供廣泛的搜尋功能、可讓您輕鬆搜尋所有連線來源的特定檔案或資料片段。BlueXP 分類可讓使用者比中繼資料所反映的內容更深入地搜尋。這項不受語言限制的服務也能讀取檔案、分析各種敏感資料類型、例如名稱和ID。例如、使用者可以搜尋結構化和非結構化的資料儲存區、找出可能從資料庫洩漏到使用者檔案的資料、違反企業原則。搜尋可儲存以供日後使用、並可建立原則以設定頻率搜尋結果並採取行動。

找到感興趣的檔案後、即可列出特性、包括標記、工作環境帳戶、儲存庫、檔案路徑、 類別（從分類）、檔案大小、上次修改、權限狀態、重複項目、 敏感度層級、個人資料、檔案內的敏感資料類型、擁有者、檔案類型、檔案大小、建立時間、 檔案雜湊、是否將資料指派給尋求注意的人員等。篩選條件可用於篩選出不相關的特性。BlueXP 分類也有 RBAC 控制項、可在有適當權限的情況下、允許移動或刪除檔案。如果沒有適當的權限存在、則可將工作指派給組織中擁有適當權限的人員。



=== BlueXP 分類提供何種分析？

資料來源可以視覺化呈現、並以圖形方式定義和描繪關係。例如、管理員可以查看整個企業內所有資料來源（內部部署系統、資料庫、檔案共用、S3儲存區、OneDrive、 等）。然後、他們可以複製、移動、刪除及管理資料、以最佳化儲存成本並降低風險。使用者可以查看哪些敏感資料可能會外洩、藉此降低風險、並建立工作來管理強大資料保護的權限。BlueXP 分類也會將所有不同類型的資料分類、讓管理員能夠依類型調查資料、並查看資料採取了哪些行動、以及何時採取行動。



=== BlueXP 分類是否提供報告？

是的。BlueXP 分類所提供的資訊可能與組織中的其他利益相關者有關、因此我們能讓您產生報告、以分享這些見解。以下報告可供 BlueXP 分類使用：

隱私權風險評估報告:: 提供資料的隱私見解和隱私權風險分數。 link:task-generating-compliance-reports.html#privacy-risk-assessment-report["深入瞭解"^]。
資料主旨存取要求報告:: 可讓您擷取包含資料主旨特定名稱或個人識別碼相關資訊之所有檔案的報告。 link:task-generating-compliance-reports.html#what-is-a-data-subject-access-request["深入瞭解"^]。
PCI DSS 報告:: 協助您辨識信用卡資訊在檔案之間的發佈情形。 link:task-generating-compliance-reports.html#pci-dss-report["深入瞭解"^]。
HIPAA 報告:: 協助您識別檔案之間的健全狀況資訊發佈。 link:task-generating-compliance-reports.html#hipaa-report["深入瞭解"^]。
資料對應報告:: 提供有關工作環境中檔案大小和數量的資訊。這包括使用容量、資料存留時間、資料大小和檔案類型。 link:task-controlling-governance-data.html#data-mapping-report["深入瞭解"^]。
資料探索評估報告:: 提供對掃描環境的高階分析、以突顯系統的發現、並顯示關切領域和可能的補救步驟。 link:task-controlling-governance-data.html#data-discovery-assessment-report["學習模式"^]。
報告特定資訊類型:: 報告中包含有關已識別檔案的詳細資料、這些檔案包含個人資料和敏感個人資料。您也可以查看依類別和檔案類型分類的檔案。 link:task-controlling-private-data.html["深入瞭解"^]。




=== 掃描效能是否有所差異？

掃描效能可能會因網路頻寬和環境中的平均檔案大小而有所不同。也可能取決於主機系統的大小特性（無論是雲端或內部部署）。請參閱 link:concept-cloud-compliance.html#the-bluexp-classification-instance["BlueXP 分類執行個體"^] 和 link:task-deploy-cloud-compliance.html["部署 BlueXP 分類"^] 以取得更多資訊。

一開始新增資料來源時、您也可以選擇只執行「對應」掃描、而非完整的「分類」掃描。您可以很快在資料來源上完成對應、因為它不會存取檔案來查看內部資料。 link:concept-cloud-compliance.html#whats-the-difference-between-mapping-and-classification-scans["瞭解對應與分類掃描之間的差異"^]。



== BlueXP 分類管理與隱私權

下列問題提供如何管理 BlueXP 分類和隱私權設定的資訊。



=== 如何啟用 BlueXP 分類？

首先、您需要在 BlueXP 或內部部署系統中部署 BlueXP 分類執行個體。執行個體執行後、您可以從 * 組態 * 標籤或選取特定工作環境、在現有工作環境、資料庫及其他資料來源上啟用服務。

link:task-getting-started-compliance.html["瞭解如何開始使用"^]。


NOTE: 在資料來源上啟動 BlueXP 分類會立即進行初始掃描。掃描結果會在不久後顯示。



=== 如何停用 BlueXP 分類？

您可以從 BlueXP 分類組態頁面、停用 BlueXP 分類、以掃描個別工作環境、資料庫、檔案共用群組、 OneDrive 帳戶或 SharePoint 帳戶。

link:task-managing-compliance.html["深入瞭解"^]。


NOTE: 若要完全移除 BlueXP 分類執行個體、您可以從雲端供應商的入口網站或內部部署位置手動移除 BlueXP 分類執行個體。



=== 我可以根據組織的需求自訂服務嗎？

BlueXP 分類提供現成的資料洞見。您可以擷取這些洞見、並將其用於貴組織的需求。

此外、 BlueXP 分類提供許多方法、讓您新增自訂的「個人資料」清單、讓 BlueXP 分類在掃描中識別、讓您完整瞭解可能敏感資料位於組織檔案的位置。

* 您可以根據您正在掃描的資料庫中的特定欄位來新增獨特的識別碼、我們稱之為*資料Fusion S16*。
* 您可以從文字檔新增自訂關鍵字。
* 您可以使用規則運算式（regex）新增自訂模式。


link:task-managing-data-fusion.html["深入瞭解"^]。



=== 我可以將 BlueXP 分類資訊限制在特定使用者嗎？

是的、 BlueXP 分類與 BlueXP 完全整合。BlueXP使用者只能根據其工作區權限、查看其符合檢視資格的工作環境資訊。

此外、如果您想讓特定使用者只檢視 BlueXP 分類掃描結果、而無法管理 BlueXP 分類設定、您可以將 Cloud Compliance Viewer 角色指派給這些使用者。

link:concept-cloud-compliance.html#user-access-to-compliance-information["深入瞭解"^]。



=== 是否有人可以存取在我的瀏覽器和 BlueXP 分類之間傳送的私有資料？

不可以在瀏覽器和 BlueXP 分類執行個體之間傳送的私有資料會以端點對端點加密來保護、這表示 NetApp 和第三方無法讀取資料。除非您要求並核准存取權限、否則 BlueXP 分類不會與 NetApp 分享任何資料或結果。



=== 如果在您的功能區上啟用資料分層、會發生什麼情況ONTAP ？

當 BlueXP 分類掃描冷資料分層到物件儲存的磁碟區時、它會掃描本機磁碟上的所有資料、以及分層到物件儲存的冷資料。對於實作分層的非 NetApp 產品來說、也是如此。

掃描不會使冷資料變熱、因為它會保持冷、並留在物件儲存區中。



=== BlueXP 分類是否可以傳送通知給我的組織？

是的。搭配原則功能、您可以在原則傳回結果時、將電子郵件警示傳送給BlueXP使用者（每日、每週或每月）或任何其他電子郵件地址、以便取得通知來保護資料。深入瞭解 link:task-using-policies.html["原則"^]。

您也可以從「治理」頁面和「調查」頁面下載狀態報告、以便在組織內部分享。



=== BlueXP 分類是否能與我的檔案中內嵌的 AIP 標籤搭配使用？

是的。如果您已訂閱、您可以在 BlueXP 分類正在掃描的檔案中管理 AIP 標籤 https://azure.microsoft.com/en-us/services/information-protection/["Azure資訊保護（AIP）"^]。您可以檢視已指派給檔案的標籤、新增標籤至檔案、以及變更現有的標籤。

link:task-org-private-data.html#categorizing-your-data-using-aip-labels["深入瞭解"^]。



== 來源系統和資料類型的類型

下列問題與可掃描的儲存設備類型及掃描的資料類型有關。



=== 可以使用 BlueXP 分類來掃描哪些資料來源？

BlueXP 分類可以掃描您新增至 BlueXP Canvas 的工作環境中的資料、以及 BlueXP 分類可透過網路存取的許多結構化和非結構化資料來源。

*工作環境：*

* （部署於AWS、Azure或GCP）Cloud Volumes ONTAP
* 內部部署 ONTAP 的叢集
* Azure NetApp Files
* Amazon FSX for ONTAP Sf
* Amazon S3


*資料來源：*

* 非NetApp檔案共用
* 物件儲存（使用S3傳輸協定）
* 資料庫（Amazon RDS、MongoDB、MySQL、Oracle、PostgreSQL、 SAP HANA、SQL Server）
* OneDrive 帳戶
* SharePoint Online和內部部署帳戶
* Google雲端硬碟帳戶


BlueXP 分類支援 NFS 3.x 、 4.0 和 4.1 版、以及 CIFS 1.x 、 2.0 、 2.1 和 3.0 版。



=== 在政府區域部署時、是否有任何限制？

當 Connector 部署在政府區域（ AWS GovCloud 、 Azure Gov 或 Azure DoD ）時、就支援 BlueXP 分類。以這種方式部署時、 BlueXP 分類具有下列限制：

* 無法掃描OneDrive帳戶、SharePoint帳戶和Google雲端硬碟帳戶。
* Microsoft Azure資訊保護（AIP）標籤功能無法整合。




=== 如果我在沒有網際網路存取的站台中安裝 BlueXP 分類、可以掃描哪些資料來源？

BlueXP 分類只能掃描內部部署站台本機資料來源的資料。此時、 BlueXP 分類可掃描「暗」網站中的下列本機資料來源：

* 內部部署ONTAP 的作業系統
* 資料庫架構
* SharePoint內部部署帳戶（SharePoint Server）
* 非NetApp NFS或CIFS檔案共用
* 使用簡易儲存服務（S3）傳輸協定的物件儲存設備




=== 支援哪些檔案類型？

BlueXP 分類會掃描所有檔案、以取得類別和中繼資料的洞見、並在儀表板的檔案類型區段中顯示所有檔案類型。

當 BlueXP 分類偵測到個人識別資訊（ PII ）、或執行 DSAR 搜尋時、僅支援下列檔案格式：

.CSV、.dcm、.dicom、.dDOC、.DOCX、 .Json、.PDF、.PPTX、.RTF、.TXT、 .XLS、.XLSX、文件、工作表及Slides +



=== BlueXP 分類擷取哪些類型的資料和中繼資料？

BlueXP 分類可讓您在資料來源上執行一般的「對應」掃描或完整的「分類」掃描。對應只提供資料的高層級總覽、而分類則提供資料的深度層級掃描。您可以很快在資料來源上完成對應、因為它不會存取檔案來查看內部資料。

* 資料對應掃描：
+
BlueXP 分類僅掃描中繼資料。這對整體資料管理與治理、快速專案範圍規劃、大型產業和優先順序都很有幫助。資料對應是以中繼資料為基礎、視為*快速*掃描。

+
快速掃描之後、您可以產生資料對應報告。本報告概述儲存在企業資料來源中的資料、協助您做出有關資源使用率、移轉、備份、安全性及法規遵循程序的決策。

* 資料分類（深度）掃描。
+
BlueXP 分類掃描會使用標準通訊協定、並在整個環境中使用唯讀權限。針對敏感的業務相關資料、私有資訊及勒索軟體相關問題、會開啟並掃描選取的檔案。

+
完成完整掃描後、您可以套用許多其他 BlueXP 分類功能至資料、例如在「資料調查」頁面中檢視及精簡資料、搜尋檔案中的名稱、複製、移動及刪除來源檔案等。





== 授權與成本

下列問題與使用 BlueXP 分類的授權和成本有關。



=== BlueXP 分類的成本是多少？

使用 BlueXP 分類的成本取決於您正在掃描的資料量。BlueXP 分類在 BlueXP 工作區中掃描的前 1 TB 資料可免費使用 30 天。達到任一上限後、您需要下列其中一項才能繼續掃描資料：

* 向您的雲端供應商訂閱BlueXP Marketplace清單、或
* NetApp的自帶授權（BYOL）


請參閱 https://bluexp.netapp.com/pricing["定價"^] 以取得詳細資料。



=== 如果我達到BYOL容量上限、會發生什麼事？

如果您達到 BYOL 容量限制、 BlueXP 分類會繼續執行、但儀表板的存取會遭到封鎖、因此您無法檢視任何已掃描資料的相關資訊。只有在您想要減少所掃描的磁碟區數量、使容量使用量可能低於授權限制時、才可使用「組態」頁面。您必須續約 BYOL 授權、才能重新取得 BlueXP 分類的完整存取權。



== 連接器部署

下列問題與BlueXP Connector有關。



=== 什麼是Connector？

Connector是在雲端帳戶內或內部部署的運算執行個體上執行的軟體、可讓BlueXP安全地管理雲端資源。您必須部署 Connector 才能使用 BlueXP 分類。



=== 連接器需要安裝在何處？

* 在Cloud Volumes ONTAP AWS、Amazon FSX for ONTAP Sf2或AWS S3儲存區中掃描資料時、您會在AWS中使用連接器。
* 在 Cloud Volumes ONTAP Azure 或 Azure NetApp Files 以不一樣的方式掃描資料時、您需要使用 Azure 中的連接器。
* 在Cloud Volumes ONTAP GCP中掃描資料時、請使用GCP中的Connector。
* 在內部部署ONTAP 的支援系統、非NetApp檔案共用、一般S3物件儲存、資料庫、OneDrive資料夾、SharePoint帳戶及Google雲端磁碟帳戶中掃描資料時、您可以在這些雲端位置中使用連接器。


因此、如果您在這些位置中有許多資料、您可能需要使用 https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html#when-to-use-multiple-connectors["多個連接器"^]。



=== 我可以在自己的主機上部署Connector嗎？

是的。您可以 https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-install-connector-on-prem.html["在內部部署連接器"^] 在您網路中的 Linux 主機或雲端中的主機上。如果您打算在內部部署部署 BlueXP 分類、則可能也想要在內部部署安裝 Connector 、但這不是必要的。



=== 沒有網際網路存取的安全網站又如何？

是的、這也受到支援。您可以 https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-quick-start-private-mode.html["在無法存取網際網路的內部部署Linux主機上部署Connector"^]。然後、您可以探索內部部署的 ONTAP 叢集和其他本機資料來源、並使用 BlueXP 分類來掃描資料。



== BlueXP 分類部署

下列問題與個別的 BlueXP 分類執行個體有關。



=== BlueXP 分類支援哪些部署模式？

BlueXP可讓使用者在幾乎任何位置掃描及報告系統、包括內部部署、雲端及混合式環境。BlueXP 分類通常是使用 SaaS 模式來部署、其中服務是透過 BlueXP 介面啟用、不需要安裝硬體或軟體。即使是在這種點選即用部署模式下、資料管理也能完成、無論資料存放區是在內部部署或公有雲中。



=== BlueXP 分類需要哪種類型的執行個體或 VM ？

何時 link:task-deploy-cloud-compliance.html["部署於雲端"]：

* 在 AWS 中、 BlueXP 分類是在 m6i.4xlarge 執行個體上執行、其中有 500 GiB GP2 磁碟。您可以在部署期間選取較小的執行個體類型。
* 在 Azure 中、 BlueXP 分類是在標準 D16s_v3 VM 上執行、其中含有 500 GB 磁碟。
* 在 GCP 中、 BlueXP 分類是在 n2-Standard-16 VM 上執行、其中含有 500 GiB Standard 持續性磁碟。


請注意、您可以在 CPU 較少且 RAM 較少的系統上部署 BlueXP 分類、但使用這些系統時會有一些限制。請參閱 link:concept-cloud-compliance.html#using-a-smaller-instance-type["使用較小的執行個體類型"] 以取得詳細資料。

link:concept-cloud-compliance.html["深入瞭解 BlueXP 分類的運作方式"^]。



=== 我可以在自己的主機上部署 BlueXP 分類嗎？

是的。您可以在網路或雲端上具有網際網路存取權的 Linux 主機上安裝 BlueXP 分類軟體。一切運作方式都一樣、您可以透過BlueXP繼續管理掃描組態和結果。請參閱 link:task-deploy-compliance-onprem.html["在內部部署部署 BlueXP 分類"] 以取得系統需求和安裝詳細資料。



=== 沒有網際網路存取的安全網站又如何？

是的、這也受到支援。您可以 link:task-deploy-compliance-dark-site.html["將 BlueXP 分類部署在內部部署網站上、但該網站無法存取網際網路"] 完全安全的網站。
