---
sidebar: sidebar 
permalink: faq-cloud-compliance.html 
keywords: faq, frequently asked questions, questions, cloud compliance, data sense 
summary: 如果您只是想要快速回答問題、這個常見問題集就能幫上忙。 
---
= 有關Cloud Data Sense的常見問題集
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果您只是想要快速回答問題、這個常見問題集就能幫上忙。



== 雲端資料感應服務

下列問題可讓您大致瞭解Cloud Data Sense。



=== 什麼是雲端資料意義？

Cloud Data Sense是一款雲端產品、採用人工智慧（AI）導向技術、可協助您瞭解資料內容、並識別儲存系統中的敏感資料。這些系統可以是您新增至BlueXP畫版的工作環境、以及Data Sense可透過網路存取的許多類型資料來源。 link:faq-cloud-compliance.html#what-sources-of-data-can-be-scanned-with-data-sense["請參閱下列完整清單"]。

Cloud Data Sense提供預先定義的參數（例如敏感資訊類型和類別）、以因應資料隱私和敏感度的新資料法規遵循要求、例如GDPR、CCPA、HIPAA等。



=== 雲端資料感測如何運作？

Cloud Data Sense會在您的BlueXP系統和儲存系統旁部署另一層人工智慧。然後掃描磁碟區、儲存區、資料庫及其他儲存帳戶上的資料、並為找到的資料洞見建立索引。Data Sense運用人工智慧和自然語言處理、而非以一般運算式和模式比對為基礎的替代解決方案。

Cloud Data Sense使用AI來提供資料的關聯式瞭解、以利準確偵測和分類。它是由AI驅動、因為它是專為現代資料類型和規模所設計。它也瞭解資料內容、以便提供強大、準確的探索和分類功能。

link:concept-cloud-compliance.html["深入瞭解Cloud Data Sense的運作方式"^]。



=== Cloud Data Sense的常見使用案例為何？

* 識別個人識別資訊（ PII ）。
* 根據 GDPR 、 CCPA 、 HIPAA 及其他資料隱私法規的要求、輕鬆找出特定資料並進行報告、以因應資料主題。
* 遵守新的及即將推出的資料隱私權法規。
* 遵守資料法規遵循與隱私權法規。
* 將資料從舊系統移轉至雲端。
* 遵守資料保留政策。


https://bluexp.netapp.com/netapp-cloud-data-sense["深入瞭解Cloud Data Sense的使用案例"^]。



=== 雲端資料感的架構如何？

無論您選擇在雲端或內部部署、Cloud Data Sense都能部署單一伺服器或叢集。伺服器透過標準傳輸協定連線至資料來源、並在Elasticsearch叢集中建立結果索引、該叢集也部署在相同的伺服器上。這可支援多個雲端、跨雲端、私有雲和內部部署環境。



=== 支援哪些雲端供應商？

Cloud Data Sense是BlueXP的一部分、支援AWS、Azure和GCP。如此一來、您的組織便能在不同的雲端供應商之間統一化隱私權可見度。



=== Cloud Data Sense是否有REST API、是否能搭配協力廠商工具使用？

BlueXP支援其服務的REST API功能。如果BlueXP不是首選的管理點、雲端資料感應等服務也可透過REST API使用。每個使用者動作都有REST API、可與協力廠商系統整合。



=== 雲端資料感應是否可透過市場取得？

是的、您可以從AWS、Azure和GCP市場取得BlueXP和Cloud Data Sense。



== 雲端資料感應掃描與分析

下列問題與Cloud Data Sense掃描效能和使用者可用的分析有關。



=== Cloud Data Sense多久掃描一次我的資料？

資料經常變更、因此Cloud Data Sense可持續掃描資料、不會對資料造成任何影響。雖然初次掃描資料可能需要較長時間、但後續掃描只會掃描遞增變更、如此可縮短系統掃描時間。

link:concept-cloud-compliance.html#how-scans-work["瞭解掃描的運作方式"]。

資料掃描對儲存系統和資料的影響微乎其微。不過、如果您擔心影響極小、您可以設定「Data Sense」（資料感測）來執行「Slow」（慢速）掃描。 link:task-reduce-scan-speed.html["瞭解如何降低掃描速度"]。



=== 我可以使用Cloud Data Sense搜尋資料嗎？

Cloud Data Sense提供廣泛的搜尋功能、可讓您輕鬆搜尋所有連線來源的特定檔案或資料。Data Sense可讓使用者進行更深入的搜尋、而不只是中繼資料所反映的內容。這項不受語言限制的服務也能讀取檔案、分析各種敏感資料類型、例如名稱和ID。例如、使用者可以搜尋結構化和非結構化的資料儲存區、找出可能從資料庫洩漏到使用者檔案的資料、違反企業原則。搜尋可儲存以供日後使用、並可建立原則以設定頻率搜尋結果並採取行動。

找到感興趣的檔案後、即可列出特性、包括標記、工作環境帳戶、儲存庫、檔案路徑、 類別（從分類）、檔案大小、上次修改、權限狀態、重複項目、 敏感度層級、個人資料、檔案內的敏感資料類型、擁有者、檔案類型、檔案大小、建立時間、 檔案雜湊、是否將資料指派給尋求注意的人員等。篩選條件可用於篩選出不相關的特性。Data Sense也具有RBAC控制項、可在有適當權限時、允許移動或刪除檔案。如果沒有適當的權限存在、則可將工作指派給組織中擁有適當權限的人員。



=== Cloud Data合理提供何種分析？

資料來源可以視覺化呈現、並以圖形方式定義和描繪關係。例如、管理員可以查看整個企業內所有資料來源（內部部署系統、資料庫、檔案共用、S3儲存區、OneDrive、 等）。然後、他們可以複製、移動、刪除及管理資料、以最佳化儲存成本並降低風險。使用者可以查看哪些敏感資料可能會外洩、藉此降低風險、並建立工作來管理強大資料保護的權限。Data Sense也會將所有不同類型的資料進行分類、讓管理員可以根據類型來調查資料、查看對資料採取的行動、以及採取的時間。



=== Cloud Data Sense是否提供報告？

是的。Cloud Data Sense所提供的資訊可能與貴組織中的其他利害關係人有關、因此我們可讓您產生報告、以分享這些見解。下列報告適用於Data Sense：

隱私權風險評估報告:: 提供資料的隱私見解和隱私權風險分數。 link:task-generating-compliance-reports.html#privacy-risk-assessment-report["深入瞭解"^]。
資料主旨存取要求報告:: 可讓您擷取包含資料主旨特定名稱或個人識別碼相關資訊之所有檔案的報告。 link:task-generating-compliance-reports.html#what-is-a-data-subject-access-request["深入瞭解"^]。
PCI DSS 報告:: 協助您辨識信用卡資訊在檔案之間的發佈情形。 link:task-generating-compliance-reports.html#pci-dss-report["深入瞭解"^]。
HIPAA 報告:: 協助您識別檔案之間的健全狀況資訊發佈。 link:task-generating-compliance-reports.html#hipaa-report["深入瞭解"^]。
資料對應報告:: 提供有關工作環境中檔案大小和數量的資訊。這包括使用容量、資料存留時間、資料大小和檔案類型。 link:task-controlling-governance-data.html#data-mapping-report["深入瞭解"^]。
報告特定資訊類型:: 報告中包含有關已識別檔案的詳細資料、這些檔案包含個人資料和敏感個人資料。您也可以查看依類別和檔案類型分類的檔案。 link:task-controlling-private-data.html["深入瞭解"^]。




=== 掃描效能是否有所差異？

掃描效能可能會因網路頻寬和環境中的平均檔案大小而有所不同。也可能取決於主機系統的大小特性（無論是雲端或內部部署）。請參閱 link:concept-cloud-compliance.html#the-cloud-data-sense-instance["Cloud Data Sense執行個體"^] 和 link:task-deploy-cloud-compliance.html["部署Cloud Data Sense"^] 以取得更多資訊。

一開始新增資料來源時、您也可以選擇只執行「對應」掃描、而非完整的「分類」掃描。您可以很快在資料來源上完成對應、因為它不會存取檔案來查看內部資料。 link:concept-cloud-compliance.html#whats-the-difference-between-mapping-and-classification-scans["瞭解對應與分類掃描之間的差異"^]。



== 雲端資料感測管理與隱私權

下列問題提供如何管理Cloud Data Sense和隱私權設定的相關資訊。



=== 如何啟用雲端資料感測？

首先、您需要在BlueXP或內部部署系統上部署Cloud Data Sense執行個體。執行個體之後、您可以從* Data Sense *標籤或選取特定工作環境、在現有的工作環境、資料庫及其他資料來源上啟用服務。

link:task-getting-started-compliance.html["瞭解如何開始使用"^]。


NOTE: 在資料來源上啟動Cloud Data Sense會立即進行初始掃描。掃描結果會在不久後顯示。



=== 如何停用Cloud Data Sense？

您可以從「Data Sense組態」頁面、停用「Cloud Data Sense」、從掃描個別工作環境、資料庫、檔案共用群組、OneDrive帳戶或SharePoint帳戶。

link:task-managing-compliance.html["深入瞭解"^]。


NOTE: 若要完全移除Cloud Data Sense執行個體、您可以從雲端供應商的入口網站或內部位置手動移除Data Sense執行個體。



=== 我可以根據組織的需求自訂服務嗎？

Cloud Data Sense可為您的資料提供隨裝即用的洞見。您可以擷取這些洞見、並將其用於貴組織的需求。

此外、Data Sense也提供許多方法、讓您新增資料感測在掃描中識別的自訂「個人資料」清單、讓您完整瞭解可能敏感資料在_all_貴組織檔案中的位置。

* 您可以根據您正在掃描的資料庫中的特定欄位來新增獨特的識別碼、我們稱之為*資料Fusion S16*。
* 您可以從文字檔新增自訂關鍵字。
* 您可以使用規則運算式（regex）新增自訂模式。


link:task-managing-data-fusion.html["深入瞭解"^]。



=== 我可以將Cloud Data Sense資訊限制在特定使用者身上嗎？

是的、Cloud Data Sense已與BlueXP完全整合。BlueXP使用者只能根據其工作區權限、查看其符合檢視資格的工作環境資訊。

此外、如果您想讓特定使用者在不管理「資料感應」設定的情況下、只檢視「資料感應」掃描結果、您可以將「Cloud Compliance Viewer」角色指派給這些使用者。

link:concept-cloud-compliance.html#user-access-to-compliance-information["深入瞭解"^]。



=== 是否有人能存取在我的瀏覽器和Data Sense之間傳送的私有資料？

不可以在瀏覽器和Data Sense執行個體之間傳送的私有資料、會以端點對端點加密來保護、這表示NetApp和第三方無法讀取。除非您申請並核准存取、否則Data Sense不會與NetApp分享任何資料或結果。



=== 如果在您的功能區上啟用資料分層、會發生什麼情況ONTAP ？

您可能想要在ONTAP 將冷資料分層儲存至物件儲存的功能區系統上啟用Cloud Data Sense。如果啟用資料分層、Data Sense會掃描磁碟上的所有資料、並將冷資料階層化至物件儲存設備。

法規遵循掃描不會將冷資料加熱、而是維持冷態並分層至物件儲存設備。



=== Cloud Data Sense可以傳送通知給我的組織嗎？

是的。搭配原則功能、您可以在原則傳回結果時、將電子郵件警示傳送給BlueXP使用者（每日、每週或每月）或任何其他電子郵件地址、以便取得通知來保護資料。深入瞭解 link:task-using-policies.html["原則"^]。

您也可以從「治理」頁面和「調查」頁面下載狀態報告、以便在組織內部分享。



=== Cloud Data Sense是否能搭配我檔案內嵌的AIP標籤運作？

是的。您可以在Cloud Data Sense正在掃描的檔案中管理AIP標籤（若已訂閱） https://azure.microsoft.com/en-us/services/information-protection/["Azure資訊保護（AIP）"^]。您可以檢視已指派給檔案的標籤、新增標籤至檔案、以及變更現有的標籤。

link:task-org-private-data.html#categorizing-your-data-using-aip-labels["深入瞭解"^]。



== 來源系統和資料類型的類型

下列問題與可掃描的儲存設備類型及掃描的資料類型有關。



=== 哪些資料來源可以透過Data Sense進行掃描？

Cloud Data Sense可掃描已新增至BlueXP畫版的工作環境中的資料、以及Data Sense可透過網路存取的多種結構化和非結構化資料來源。

*工作環境：*

* （部署於AWS、Azure或GCP）Cloud Volumes ONTAP
* 內部部署 ONTAP 的叢集
* Azure NetApp Files
* Amazon FSX for ONTAP Sf
* Amazon S3


*資料來源：*

* 非NetApp檔案共用
* 物件儲存（使用S3傳輸協定）
* 資料庫（Amazon RDS、MongoDB、MySQL、Oracle、PostgreSQL、 SAP HANA、SQL Server）
* OneDrive 帳戶
* SharePoint Online和內部部署帳戶
* Google雲端硬碟帳戶


Data Sense支援NFS 3.x、4.0及4.1版、以及CIFS 1.x、2.0、2.1及3.0版。



=== 在政府區域部署時、是否有任何限制？

當連接器部署於政府區域（AWS GovCloud、Azure Gov或Azure DoD）時、即可支援Cloud Data Sense。以這種方式部署時、Data Sense會有下列限制：

* 無法掃描OneDrive帳戶、SharePoint帳戶和Google雲端硬碟帳戶。
* Microsoft Azure資訊保護（AIP）標籤功能無法整合。




=== 如果我在沒有網際網路存取的網站上安裝Data Sense、我可以掃描哪些資料來源？

Data Sense只能掃描內部部署站台本機資料來源的資料。此時、Data Sense可掃描「暗」站台中的下列本機資料來源：

* 內部部署ONTAP 的作業系統
* 資料庫架構
* SharePoint內部部署帳戶（SharePoint Server）
* 非NetApp NFS或CIFS檔案共用
* 使用簡易儲存服務（S3）傳輸協定的物件儲存設備




=== 支援哪些檔案類型？

Cloud Data Sense會掃描所有檔案以取得類別和中繼資料深入資訊、並在儀表板的「檔案類型」區段中顯示所有檔案類型。

當Data Sense偵測到個人識別資訊（PII）、或執行DSAR搜尋時、僅支援下列檔案格式：

.CSV、.dcm、.dicom、.dDOC、.DOCX、 .Json、.PDF、.PPTX、.RTF、.TXT、 .XLS、.XLSX、文件、工作表及Slides +



=== Cloud Data Sense擷取哪些類型的資料和中繼資料？

Cloud Data Sense可讓您對資料來源執行一般的「對應」掃描或完整的「分類」掃描。對應只提供資料的高層級總覽、而分類則提供資料的深度層級掃描。您可以很快在資料來源上完成對應、因為它不會存取檔案來查看內部資料。

* 資料對應掃描：
+
Data Sense只會掃描中繼資料。這對整體資料管理與治理、快速專案範圍規劃、大型產業和優先順序都很有幫助。資料對應是以中繼資料為基礎、視為*快速*掃描。

+
快速掃描之後、您可以產生資料對應報告。本報告概述儲存在企業資料來源中的資料、協助您做出有關資源使用率、移轉、備份、安全性及法規遵循程序的決策。

* 資料分類（深度）掃描。
+
在整個環境中使用標準傳輸協定和唯讀權限進行資料感應掃描。針對敏感的業務相關資料、私有資訊及勒索軟體相關問題、會開啟並掃描選取的檔案。

+
完整掃描之後、您可以將許多其他Data Sense功能套用至資料、例如在「Data Investigation」（資料調查）頁面中檢視及精簡資料、在檔案中搜尋名稱、複製、移動及刪除來源檔案等。





== 授權與成本

下列問題與使用Cloud Data Sense的授權和成本有關。



=== Cloud Data合理的成本是多少？

使用Cloud Data Sense的成本取決於您要掃描的資料量。在BlueXP工作區中、Data Sense掃描的前1 TB資料是免費的30天。達到任一上限後、您需要下列其中一項才能繼續掃描資料：

* 向您的雲端供應商訂閱BlueXP Marketplace清單、或
* NetApp的自帶授權（BYOL）


請參閱 https://bluexp.netapp.com/pricing["定價"^] 以取得詳細資料。



=== 如果我達到BYOL容量上限、會發生什麼事？

如果您達到BYOL容量限制、Data Sense會繼續執行、但儀表板的存取會遭到封鎖、因此您無法檢視任何掃描資料的相關資訊。只有在您想要減少所掃描的磁碟區數量、使容量使用量可能低於授權限制時、才可使用「組態」頁面。您必須續約BYOL授權、才能重新取得Data Sense的完整存取權。



== 連接器部署

下列問題與BlueXP Connector有關。



=== 什麼是Connector？

Connector是在雲端帳戶內或內部部署的運算執行個體上執行的軟體、可讓BlueXP安全地管理雲端資源。您必須部署Connector才能使用Cloud Data Sense。



=== 連接器需要安裝在何處？

* 在Cloud Volumes ONTAP AWS、Amazon FSX for ONTAP Sf2或AWS S3儲存區中掃描資料時、您會在AWS中使用連接器。
* 在 Cloud Volumes ONTAP Azure 或 Azure NetApp Files 以不一樣的方式掃描資料時、您需要使用 Azure 中的連接器。
* 在Cloud Volumes ONTAP GCP中掃描資料時、請使用GCP中的Connector。
* 在內部部署ONTAP 的支援系統、非NetApp檔案共用、一般S3物件儲存、資料庫、OneDrive資料夾、SharePoint帳戶及Google雲端磁碟帳戶中掃描資料時、您可以在這些雲端位置中使用連接器。


因此、如果您在這些位置中有許多資料、您可能需要使用 https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html#when-to-use-multiple-connectors["多個連接器"^]。



=== 我可以在自己的主機上部署Connector嗎？

是的。您可以 https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-installing-linux.html["在內部部署連接器"^] 在網路或雲端的Linux主機上。如果您打算在內部部署Data Sense、則可能也想在內部部署安裝Connector、但這不是必要的。



=== 沒有網際網路存取的安全網站又如何？

是的、這也受到支援。您可以 https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-install-connector-onprem-no-internet.html["在無法存取網際網路的內部部署Linux主機上部署Connector"^]。然後您可以探索內部部署ONTAP 的叢集和其他本機資料來源、並使用Data Sense掃描資料。



== 資料感測部署

下列問題與個別的Data Sense執行個體有關。



=== Cloud Data Sense支援哪些部署模式？

BlueXP可讓使用者在幾乎任何位置掃描及報告系統、包括內部部署、雲端及混合式環境。Cloud Data Sense通常是使用SaaS模式來部署、在這種模式中、服務是透過BlueXP介面來啟用、不需要安裝硬體或軟體。即使是在這種點選即用部署模式下、資料管理也能完成、無論資料存放區是在內部部署或公有雲中。



=== Cloud Data Sense需要哪種類型的執行個體或VM？

何時 link:task-deploy-cloud-compliance.html["部署於雲端"]：

* 在AWS中、Cloud Data Sense可在具有500 GB GP2磁碟的m5.4x大型 執行個體上執行。
* 在Azure中、Cloud Data Sense可在具有512 GB磁碟的Standard_D16s_v3 VM上執行。
* 在GCP中、Cloud Data Sense可在具有512 GB標準持續磁碟的n2-Standard-16 VM上執行。


請注意、您可以在CPU較少、RAM較少的系統上部署Data Sense、但使用這些系統時仍有限制。請參閱 link:concept-cloud-compliance.html#using-a-smaller-instance-type["使用較小的執行個體類型"] 以取得詳細資料。

link:concept-cloud-compliance.html["深入瞭解Cloud Data Sense的運作方式"^]。



=== 我可以在自己的主機上部署Data Sense嗎？

是的。您可以將Data Sense軟體安裝在可在網路或雲端存取網際網路的Linux主機上。一切運作方式都一樣、您可以透過BlueXP繼續管理掃描組態和結果。請參閱 link:task-deploy-compliance-onprem.html["在內部部署Cloud Data Sense"] 以取得系統需求和安裝詳細資料。



=== 沒有網際網路存取的安全網站又如何？

是的、這也受到支援。您可以 link:task-deploy-compliance-dark-site.html["在無法存取網際網路的內部部署網站上部署Data Sense"] 完全安全的網站。
