---
settings:
  name: Cloud Data Sense
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: zh-tw,us-en,ja-jp,ko-kr,zh-cn,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Cloud Data Sense文件
    url: "/index.html"
  - title: 版本資訊
    url: "/whats-new.html"
  - title: 開始使用
    entries:
    - title: 深入瞭解Cloud Data Sense
      url: "/concept-cloud-compliance.html"
    - title: 部署Cloud Data Sense
      entries:
      - title: 使用BlueXP在雲端部署
        url: "/task-deploy-cloud-compliance.html"
      - title: 安裝在可存取網際網路的Linux主機上
        url: "/task-deploy-compliance-onprem.html"
      - title: 在內部安裝、無需網際網路存取
        url: "/task-deploy-compliance-dark-site.html"
      - title: 檢查您的 Linux 主機是否已準備好安裝 Data Sense
        url: "/task-test-linux-system.html"
    - title: 啟動資料來源的掃描
      entries:
      - title: 不只是內部和內部的Cloud Volumes ONTAP ONTAP
        url: "/task-getting-started-compliance.html"
      - title: Azure NetApp Files
        url: "/task-scanning-anf.html"
      - title: Amazon FSX for ONTAP Sf
        url: "/task-scanning-fsx.html"
      - title: Amazon S3 儲存桶
        url: "/task-scanning-s3.html"
      - title: 資料庫架構
        url: "/task-scanning-databases.html"
      - title: OneDrive 帳戶
        url: "/task-scanning-onedrive.html"
      - title: SharePoint帳戶
        url: "/task-scanning-sharepoint.html"
      - title: Google雲端硬碟帳戶
        url: "/task-scanning-google-drive.html"
      - title: 檔案共用
        url: "/task-scanning-file-shares.html"
      - title: 物件儲存
        url: "/task-scanning-object-storage.html"
    - title: 整合Active Directory
      url: "/task-add-active-directory-datasense.html"
    - title: 設定授權
      url: "/task-licensing-datasense.html"
    - title: 常見問題集
      url: "/faq-cloud-compliance.html"
  - title: 使用Cloud Data Sense
    entries:
    - title: 檢視資料的治理詳細資料
      url: "/task-controlling-governance-data.html"
    - title: 檢視資料的法規遵循詳細資料
      url: "/task-controlling-private-data.html"
    - title: 私有資料類別
      url: "/reference-private-data-categories.html"
    - title: 調查您的資料
      url: "/task-investigate-data.html"
    - title: 組織您的私有資料
      url: "/task-org-private-data.html"
    - title: 指派原則給您的資料
      url: "/task-using-policies.html"
    - title: 管理您的私有資料
      url: "/task-managing-highlights.html"
    - title: 變更掃描設定
      url: task-managing-repo-scanning.html
    - title: 產生法規遵循報告
      url: "/task-generating-compliance-reports.html"
  - title: 管理雲端資料感測
    entries:
    - title: 新增自訂個人資料識別碼
      url: "/task-managing-data-fusion.html"
    - title: 檢視Data Sense行動的狀態
      url: "/task-view-compliance-actions.html"
    - title: 稽核「資料感測」行動的歷史記錄
      url: "/task-audit-data-sense-actions.html"
    - title: 降低資料感應掃描速度
      url: "/task-reduce-scan-speed.html"
    - title: 從Data Sense移除資料來源
      url: "/task-managing-compliance.html"
    - title: 解除安裝Data Sense
      url: "/task-uninstall-data-sense.html"
  - title: 參考資料
    entries:
    - title: 支援的 Data Sense 執行個體類型
      url: "/reference-instance-types.html"
    - title: 從資料來源收集的中繼資料
      url: "/reference-collected-metadata.html"
  - title: 知識與支援
    entries:
    - title: 註冊以取得支援
      url: "/task-support-registration.html"
    - title: 取得協助
      url: "/task-get-help.html"
  - title: 法律聲明
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 開始使用
    links:
    - title: 深入瞭解Cloud Data Sense
      url: concept-cloud-compliance.html
    - title: 新增功能
      url: whats-new.html
    - title: 使用 BlueXP 在雲端部署 Data Sense
      url: task-deploy-cloud-compliance.html
    - title: 在具有網際網路的 Linux 主機上安裝 Data Sense
      url: task-deploy-compliance-onprem.html
    - title: 在內部部署安裝 Data Sense 、不需使用網際網路
      url: task-deploy-compliance-dark-site.html
    - title: 整合Active Directory
      url: task-add-active-directory-datasense.html
    - title: 設定授權
      url: task-licensing-datasense.html
  - title: 掃描您的工作環境
    links:
    - title: 資料量Cloud Volumes ONTAP
      url: task-getting-started-compliance.html
    - title: 內部部署ONTAP 的功能
      url: task-getting-started-compliance.html
    - title: 資料量 Azure NetApp Files
      url: task-scanning-anf.html
    - title: Amazon FSX for ONTAP Sf6 Volume
      url: task-scanning-fsx.html
    - title: Amazon S3 儲存桶
      url: task-scanning-s3.html
  - title: 掃描其他資料來源
    links:
    - title: 一般S3儲存桶
      url: task-scanning-object-storage.html
    - title: 非NetApp檔案共用
      url: task-scanning-file-shares.html
    - title: 資料庫架構
      url: task-scanning-databases.html
    - title: OneDrive 帳戶
      url: task-scanning-onedrive.html
    - title: SharePoint帳戶
      url: task-scanning-sharepoint.html
    - title: Google雲端硬碟帳戶
      url: task-scanning-google-drive.html
  - title: 檢視資料的詳細資料
    links:
    - title: 檢視包含私人資訊的檔案
      url: task-controlling-private-data.html
    - title: 檢視儲存設備中重複的檔案
      url: task-investigate-data.html#checking-for-duplicate-files-in-your-storage-systems
    - title: 篩選資料以檢視特定檔案
      url: task-investigate-data.html
    - title: 建立原則以檢視您的熱門搜尋
      url: task-using-policies.html
    - title: 產生法規遵循報告
      url: task-generating-compliance-reports.html
  - title: 組織您的私有資料
    links:
    - title: 將標記和擁有者套用至需要注意的檔案
      url: task-org-private-data.html#applying-tags-to-manage-your-scanned-files
    - title: 使用AIP標籤將資料分類
      url: task-org-private-data.html#categorizing-your-data-using-aip-labels
    - title: 新增您自己的自訂個人資料識別碼
      url: task-managing-data-fusion.html
  - title: 管理您的私有資料
    links:
    - title: 複製來源檔案
      url: task-managing-highlights.html#copying-source-files
    - title: 移動來源檔案
      url: task-managing-highlights.html#moving-source-files-to-an-nfs-share
    - title: 刪除來源檔案
      url: task-managing-highlights.html#deleting-source-files
    - title: 找到不合規的資料時、請建立電子郵件警示
      url: task-using-policies.html#sending-email-alerts-when-non-compliant-data-is-found
    - title: 回應資料主旨存取要求
      url: task-generating-compliance-reports.html#searching-for-data-subjects-and-downloading-reports
  - title: 部落格社群
    links:
    - title: NetApp社群
      url: https://community.netapp.com/t5/BlueXP-and-Services/ct-p/CDS
    - title: 資料感知使用案例
      url: https://bluexp.netapp.com/netapp-cloud-data-sense
    - title: BlueXP部落格
      url: https://bluexp.netapp.com/blog
    - title: 雲端網路研討會
      url: https://bluexp.netapp.com/events
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: 所有BlueXP文件
