---
settings:
  name: BlueXP classification
  platform: cloud
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: zh-tw,us-en,ja-jp,ko-kr,zh-cn,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: BlueXP 分類文件
    url: "/index.html"
  - title: 版本資訊
    entries:
    - title: 新增功能
      url: "/whats-new.html"
    - title: 已知限制
      url: "/reference-limitations.html"
  - title: 開始使用
    entries:
    - title: 瞭解 BlueXP 分類
      url: "/concept-cloud-compliance.html"
    - title: 部署 BlueXP 分類
      entries:
      - title: 您應該使用哪種部署
        url: "/task-deploy-overview.html"
      - title: 使用BlueXP在雲端部署
        url: "/task-deploy-cloud-compliance.html"
      - title: 安裝在可存取網際網路的Linux主機上
        url: "/task-deploy-compliance-onprem.html"
      - title: 在內部部署的 Linux 主機上安裝、無需存取網際網路
        url: "/task-deploy-compliance-dark-site.html"
      - title: 檢查您的 Linux 主機是否已準備好安裝 BlueXP 分類
        url: "/task-test-linux-system.html"
    - title: 啟動資料來源的掃描
      entries:
      - title: 不只是內部和內部的Cloud Volumes ONTAP ONTAP
        url: "/task-getting-started-compliance.html"
      - title: Azure NetApp Files
        url: "/task-scanning-anf.html"
      - title: Amazon FSX for ONTAP Sf
        url: "/task-scanning-fsx.html"
      - title: Amazon S3 儲存桶
        url: "/task-scanning-s3.html"
      - title: 資料庫架構
        url: "/task-scanning-databases.html"
      - title: OneDrive 帳戶
        url: "/task-scanning-onedrive.html"
      - title: SharePoint帳戶
        url: "/task-scanning-sharepoint.html"
      - title: Google雲端硬碟帳戶
        url: "/task-scanning-google-drive.html"
      - title: 檔案共用
        url: "/task-scanning-file-shares.html"
      - title: 物件儲存
        url: "/task-scanning-object-storage.html"
    - title: 整合Active Directory
      url: "/task-add-active-directory-datasense.html"
    - title: 設定授權
      url: "/task-licensing-datasense.html"
    - title: 常見問題集
      url: "/faq-cloud-compliance.html"
  - title: 使用 BlueXP 分類
    entries:
    - title: 檢視資料的治理詳細資料
      url: "/task-controlling-governance-data.html"
    - title: 檢視資料的法規遵循詳細資料
      url: "/task-controlling-private-data.html"
    - title: 私有資料類別
      url: "/reference-private-data-categories.html"
    - title: 調查您的資料
      url: "/task-investigate-data.html"
    - title: 組織您的私有資料
      url: "/task-org-private-data.html"
    - title: 指派原則給您的資料
      url: "/task-using-policies.html"
    - title: 管理您的私有資料
      url: "/task-managing-highlights.html"
    - title: 變更掃描設定
      url: task-managing-repo-scanning.html
    - title: 產生法規遵循報告
      url: "/task-generating-compliance-reports.html"
  - title: 管理 BlueXP 分類
    entries:
    - title: 新增自訂個人資料識別碼
      url: "/task-managing-data-fusion.html"
    - title: 將目錄排除在掃描之外
      url: "/task-exclude-scan-paths.html"
    - title: 檢視 BlueXP 分類動作的狀態
      url: "/task-view-compliance-actions.html"
    - title: 將現有的群組 ID 定義為「開放給組織」
      url: "/task-add-group-id-as-open.html"
    - title: 稽核 BlueXP 分類動作的歷史記錄
      url: "/task-audit-data-sense-actions.html"
    - title: 降低 BlueXP 分類掃描速度
      url: "/task-reduce-scan-speed.html"
    - title: 從 BlueXP 分類中移除資料來源
      url: "/task-managing-compliance.html"
    - title: 解除安裝 BlueXP 分類
      url: "/task-uninstall-data-sense.html"
  - title: 參考資料
    entries:
    - title: 支援的 BlueXP 分類執行個體類型
      url: "/reference-instance-types.html"
    - title: 從資料來源收集的中繼資料
      url: "/reference-collected-metadata.html"
    - title: 登入 BlueXP 分類系統
      url: "/reference-log-in-to-instance.html"
    - title: BlueXP 分類 API
      url: "/api-classification.html"
  - title: 知識與支援
    entries:
    - title: 註冊以取得支援
      url: "/task-support-registration.html"
    - title: 取得協助
      url: "/task-get-help.html"
  - title: 法律聲明
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
