---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, data sense, classification, bluexp, scan shares 
summary: 已知限制標識了此版本產品不支援的功能或無法與其正確互通的功能。請仔細檢閱這些限制。 
---
= BlueXP  分類的已知限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
已知限制標識了此版本中不受支援或無法正確互通的功能。請仔細檢閱這些限制。



== BlueXP 分類停用選項

2023 年 12 月（版本 1.26.6 ）版本移除下列選項：

* 啟用稽核記錄集合的選項已停用。
* 在目錄調查期間，無法使用目錄計算個人識別資訊 (PII) 資料數量的選項。
* 已停用使用 Azure Information Protection （ AIP ）標籤整合資料的選項。




== BlueXP分類掃描

BlueXP 分類掃描有以下限制。



=== BlueXP 分類只會掃描一個磁碟區下的一個共用區

如果單一磁碟區下有多個檔案共用、 BlueXP 分類會以最高階層掃描共用。例如、如果您有類似下列的共用：

* /a
* /A/B
* /C
* /D/E


在此配置中，僅掃描 /A 中的資料。不掃描 /C 和 /D 中的資料。

.因應措施
有一種因應措施可確保您掃描的資料來自 Volume 中的所有共用區。請遵循下列步驟：

. 在工作環境中、新增要掃描的 Volume 。
. BlueXP 分類完成掃描磁碟區後、請前往 _Data Investigation 頁面並建立篩選器、查看要掃描的共用區：
+
透過「工作環境名稱」和「目錄類型 = 共享」過濾數據，以查看正在掃描哪個共享。

. 取得 Volume 中存在的完整共用清單、以便查看哪些共用未被掃描。
. link:task-scanning-file-shares.html["將剩餘的共用新增至共用群組"]。
+
單獨新增所有共享，例如：

+
....
/C
/D
....
. 針對工作環境中具有多個共用區的每個磁碟區執行這些步驟。




=== 上次訪問的時間戳

當 BlueXP 分類對目錄進行掃描時，該掃描會影響目錄的「上次存取時間」欄位。當您查看「上次造訪時間」欄位時，該元資料會反映掃描的日期和時間，或使用者上次造訪該目錄的時間。
