---
sidebar: sidebar 
permalink: task-audit-data-sense-actions.html 
keywords: compliance, actions, view progress, audit, logs, installation 
summary: Data Sense會記錄所有工作環境中的檔案、以及Data Sense正在掃描的資料來源所執行的管理活動。Data Sense也會在部署Data Sense執行個體時記錄活動。 
---
= 稽核Data Sense動作的歷程記錄
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Data Sense會記錄所有工作環境中的檔案、以及Data Sense正在掃描的資料來源所執行的管理活動。Data Sense也會在部署Data Sense執行個體時記錄活動。

您可以檢視Data Sense稽核記錄檔的內容、或是下載這些檔案、以查看發生了哪些檔案變更、以及何時發生。例如、您可以查看發出的要求、要求時間、以及檔案刪除時的來源位置、或檔案移動時的來源和目的地位置等詳細資料。



== 記錄檔內容

稽核記錄中的每一行都包含下列格式的資訊：

`<full date> | <status> | ds_audit_logger | <module> | 0 | 0 | File <full file path> deleted from device <device path> - <result>`

* 日期與時間：事件的完整時間戳記
* 狀態-資訊、警告
* 行動類型（刪除、複製、移動、建立原則、更新原則、 重新掃描檔案、下載Json報告等）
* 檔案名稱（如果動作與檔案相關）
* 行動的詳細資料：做了什麼：取決於行動
+
** 原則名稱
** 用於移動-來源和目的地
** 複本：來源和目的地
** 用於標記-標記名稱
** 指派給-使用者名稱
** 電子郵件警示：電子郵件地址/帳戶




例如、記錄檔中的下列行顯示複製作業成功、複製作業失敗。

....
2022-06-06 15:23:08,910 | INFO | ds_audit_logger | es_scanned_file | 237 | 49 | Copy file /CIFS_share/data/dop1/random_positives.tsv from device 10.31.133.183 (type: SMB_SHARE) to device 10.31.130.133:/export_reports (NFS_SHARE) - SUCCESS
2022-06-06 15:23:08,968 | WARNING | ds_audit_logger | es_scanned_file | 239 | 153 | Copy file /CIFS_share/data/compliance-netapp.tar.gz from device 10.31.133.183 (type: SMB_SHARE) to device 10.31.130.133:/export_reports (NFS_SHARE) - FAILURE
....


== 存取記錄檔

管理稽核記錄檔位於Data Sense機器上、位於： `/opt/netapp/audit_logs/`

安裝稽核記錄檔會寫入 `/ops/netapp/install_logs`

每個記錄檔的大小上限為10 MB。達到該限制時、會啟動新的記錄檔。記錄檔的名稱為「DataSense_nap稽 核.log」、「DataSense_nap稽 核.log.1」、「DataSense_nap審查.log.2」等。系統最多可保留100個記錄檔-在達到上限後、會自動刪除舊的記錄檔。

當 Data Sense 安裝在內部部署的 Linux 機器上、或部署在雲端的 Linux 機器上時、您可以直接瀏覽至記錄檔。

在雲端部署Data Sense時、您需要SSH到Data Sense執行個體。您可以輸入使用者和密碼、或使用您在安裝BlueXP Connector期間提供的SSH金鑰來SSH到系統。SSH命令是：

 ssh -i <path_to_the_ssh_key> <machine_user>@<datasense_ip>
* <path_to_the_ssh驗證金鑰>= ssh驗證金鑰的位置
* <machine_user>：
+
** 對於AWS：使用<EC2-user>
** Azure：使用為BlueXP執行個體建立的使用者
** GCP：使用為BlueXP執行個體建立的使用者


* <datasense_ip>=虛擬機器執行個體的IP位址


請注意、您需要修改安全群組傳入規則、才能存取雲端中的系統。如需詳細資料、請參閱：

* https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-ports-aws.html["AWS中的安全群組規則"^]
* https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-ports-azure.html["Azure中的安全性群組規則"^]
* https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-ports-gcp.html["Google Cloud中的防火牆規則"^]

