---
sidebar: sidebar 
permalink: task-test-linux-system.html 
keywords: cloud compliance, bluexp, data sense, get started, deploy, bluexp classification, cloud compliance access, compliance, on-premises, linux, test linux system, docker, podman, ubuntu, rhel, dark site, bluexp 
summary: 在 Linux 主機上手動安裝 BlueXP 分類之前、您可以在主機上執行指令碼、以確認安裝 BlueXP 分類的所有必要條件均已就緒。您可以在網路中的 Linux 主機或雲端中的 Linux 主機上執行此指令碼。主機可以連線至網際網路、或者主機可以位於無法存取網際網路的站台。 
---
= 檢查您的 Linux 主機是否已準備好安裝 BlueXP 分類
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在 Linux 主機上手動安裝 BlueXP  分類之前，請選擇性地在主機上執行指令碼，以確認安裝 BlueXP  分類的所有必要條件均已就緒。您可以在網路中的 Linux 主機或雲端中的 Linux 主機上執行此指令碼。主機可以連線至網際網路、或主機可以位於無法存取網際網路的站台（暗站台）。

還有一個先決條件測試指令碼是 BlueXP 分類安裝指令碼的一部分。此處說明的指令碼是專為想要驗證 Linux 主機而不執行 BlueXP 分類安裝指令碼的使用者所設計。



== 快速入門

您將執行下列工作。

. 或者、如果您尚未安裝 BlueXP Connector 、請安裝該連接器。您可以在不安裝 Connector 的情況下執行測試指令碼、但指令碼會檢查 Connector 和 BlueXP 分類主機之間的連線、因此建議您使用 Connector 。
. 準備主機並確認它符合所有需求。
. 從 BlueXP 分類主機機器啟用輸出網際網路存取。
. 確認所有系統上的所有必要連接埠都已啟用。
. 下載並執行先決條件測試指令碼。




== 建立連接器

安裝和使用 BlueXP 分類之前、需要 BlueXP Connector 。不過、您可以在沒有 Connector 的情況下執行 Prerequisites 指令碼。

您可以 https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-on-prem.html["在內部部署安裝連接器"^]在網路中的 Linux 主機或雲端中的 Linux 主機上執行。有些打算在內部部署上安裝 BlueXP 分類的使用者也可以選擇在內部部署上安裝 Connector 。

若要在雲端供應商環境中建立 Connector ，請參閱 https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-aws.html["在AWS中建立連接器"^]， https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-azure.html["在 Azure 中建立 Connector"^]或 https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-google.html["在GCP中建立連接器"^]。

執行 Prerequisites 指令碼時、您需要 Connector 系統的 IP 位址或主機名稱。如果您在內部部署中安裝了Connector、您將會獲得這些資訊。如果連接器部署在雲端、您可以從BlueXP主控台找到這項資訊：按一下「說明」圖示、選取*「支援*」、然後按一下「* BlueXP Connector*」。



== 驗證主機需求

BlueXP 分類軟體必須在符合特定作業系統需求、 RAM 需求、軟體需求等的主機上執行。

* 與其他應用程式共用的主機不支援 BlueXP 分類、主機必須是專用主機。
* 在內部環境中建置主機系統時、您可以根據計畫執行 BlueXP 分類掃描的資料集大小、從這些系統大小中進行選擇。
+
[cols="17,17,27,31"]
|===
| 系統大小 | CPU | RAM（交換記憶體必須停用） | 磁碟 


| * 超大 * | 32 個 CPU | 128 GB RAM  a| 
** 1 個 TiB SSD on / ，或 100 GiB 可在 /opt 上取得
** /var/lib/泊 塢視窗上提供 895 GiB
** 5 GiB、位於/tmp
** * 對於播客， 5 GB 位於 /tmp* 上
** * 對於播客， /var/tmp* 上有 30 GB




| * 大 * | 16 個 CPU | 64 GB RAM  a| 
** 500 GiB SSD on / ，或 100 GiB 可在 /opt 上取得
** 395 GiB 可在 /var/lib/泊 塢視窗或 Podcast man /var/lib/container 或 Podman /var/lib/container 上取得
** 5 GiB、位於/tmp
** * 對於播客， 5 GB 位於 /tmp* 上
** * 對於播客， /var/tmp* 上有 30 GB


|===
* 在雲端部署運算執行個體以進行 BlueXP 分類安裝時、我們建議系統符合上述「大型」系統需求：
+
** * Amazon Elastic Compute Cloud （ Amazon EC2 ）執行個體類型 * ：我們建議使用「 m6i.4xLarge 」。link:reference-instance-types.html#aws-instance-types["請參閱其他 AWS 執行個體類型"^]。
** * Azure VM Size* ：我們建議使用「 Standard_D16s_v3 」。link:reference-instance-types.html#azure-instance-types["請參閱其他 Azure 執行個體類型"^]。
** * GCP 機器類型 * ：我們建議使用「 n2-Standard-16 」。link:reference-instance-types.html#gcp-instance-types["請參閱其他 GCP 執行個體類型"^]。


* * UNIX 資料夾權限 * ：需要下列最低 UNIX 權限：
+
[cols="25,25"]
|===
| 資料夾 | 最低權限 


| /tmp | `rwxrwxrwt` 


| /opt | `rwxr-xr-x` 


| /var/lib/泊 塢視窗 | `rwx------` 


| /usr/lib/systemd/system | `rwxr-xr-x` 
|===
* * 作業系統 * ：
+
** 下列作業系統需要使用 Docker Container 引擎：
+
*** Red Hat Enterprise Linux 版本 7.8 和 7.9
*** Ubuntu 22.04 （需要 BlueXP 分級版本 1.23 或更新版本）
*** Ubuntu 24.04 （需要 BlueXP 分級版本 1.23 或更新版本）


** 下列作業系統需要使用 Podman Container 引擎、而且需要 BlueXP 分類版本 1.30 或更新版本：
+
*** Red Hat Enterprise Linux 版本 8.8 ， 8.10 ， 9.0 ， 9.1 ， 9.2 ， 9.3 ， 9.4 和 9.5


** 必須在主機系統上啟用進階向量擴充 (AVX2)。


* * Red Hat Subscription Management* ：主機必須向 Red Hat Subscription Management 註冊。如果系統尚未註冊、則無法在安裝期間存取儲存庫以更新所需的協力廠商軟體。
* * 其他軟體 * ：安裝 BlueXP 分類之前、您必須在主機上安裝下列軟體：
+
** 視您使用的作業系統而定、您需要安裝其中一個容器引擎：
+
*** Docker Engine 版本 19.3.1 或更新版本。 https://docs.docker.com/engine/install/["檢視安裝指示"^]。
*** Podman 版本 4 或更新版本。若要安裝 Podman 、請輸入 (`sudo yum install podman netavark -y`）。






* Python 3.6 版或更新版本。 https://www.python.org/downloads/["檢視安裝指示"^]。
+
** * NTP 考量 * ： NetApp 建議將 BlueXP 分類系統設定為使用網路時間傳輸協定（ NTP ）服務。必須在 BlueXP 分類系統和 BlueXP Connector 系統之間同步時間。




* * Firewwalld 注意事項 * ：如果您打算使用 `firewalld`，建議您在安裝 BlueXP  分類之前先啟用。執行下列命令以進行設定 `firewalld`，使其與 BlueXP  分類相容：
+
....
firewall-cmd --permanent --add-service=http
firewall-cmd --permanent --add-service=https
firewall-cmd --permanent --add-port=80/tcp
firewall-cmd --permanent --add-port=8080/tcp
firewall-cmd --permanent --add-port=443/tcp
firewall-cmd --reload
....
+
如果您打算使用其他 BlueXP 分類主機做為掃描器節點（分散式機型）、請在此時將這些規則新增至主要系統：

+
....
firewall-cmd --permanent --add-port=2377/tcp
firewall-cmd --permanent --add-port=7946/udp
firewall-cmd --permanent --add-port=7946/tcp
firewall-cmd --permanent --add-port=4789/udp
....
+
請注意，每當您啟用或更新設定時，都必須重新啟動 Docker 或 Podman `firewalld` 。





== 從 BlueXP 分類啟用輸出網際網路存取

BlueXP 分類需要外傳網際網路存取。如果您的虛擬或實體網路使用 Proxy 伺服器進行網際網路存取、請確定 BlueXP 分類執行個體具有傳出網際網路存取權、以聯絡下列端點。


TIP: 如果站台中安裝的主機系統沒有網際網路連線、則不需要此區段。

[cols="43,57"]
|===
| 端點 | 目的 


| \https://api.bluexp.netapp.com | 與包括NetApp帳戶在內的BlueXP服務通訊。 


| https ： NetApp-cloud-account.auth0.com \https://auth0.com | 與BlueXP網站通訊以進行集中式使用者驗證。 


| https://support.compliance.api 。 BlueXP  。 NetApp 。 com/ \https://hub.docker.com \https://auth.docker.io \https://registry-1.docker.io \https://index.docker.io/ \https://dseasb33srnrn.cloudfront.net/ \https://production.cloudflare.docker.com/ | 提供軟體映像、資訊清單、範本的存取、以及傳送記錄和度量資料的功能。 


| https://support.compliance.api 。 BlueXP  。 NetApp 。 com/ | 讓 NetApp 能夠從稽核記錄串流資料。 


| https://github.com/docker \https://download.docker.com | 提供泊塢視窗安裝的必要套件。 


| \http://packages.ubuntu.com/ \http://archive.ubuntu.com | 提供 Ubuntu 安裝的必要套件。 
|===


== 確認已啟用所有必要的連接埠

您必須確保所有必要的連接埠都已開啟、以便在 Connector 、 BlueXP 分類、 Active Directory 和資料來源之間進行通訊。

[cols="25,25,50"]
|===
| 連線類型 | 連接埠 | 說明 


| Connector <> BlueXP 分類 | 8080 （ TCP ）、 443 （ TCP ）和 80 。9000 | Connector 的防火牆或路由規則必須允許透過連接埠 443 進出的流量進出 BlueXP 分類執行個體。請確定連接埠8080已開啟、以便您在BlueXP中查看安裝進度。如果在 Linux 主機上使用防火牆、則 Ubuntu 伺服器內部程序需要連接埠 9000 。 


| 連接器<> ONTAP -叢集（NAS） | 443（TCP）  a| 
BlueXP會使用ONTAP HTTPS探索叢集。如果您使用自訂防火牆原則、 Connector 主機必須允許透過連接埠 443 進行輸出 HTTPS 存取。如果連接器位於雲端、則預先定義的防火牆或路由規則會允許所有傳出通訊。

|===


== 執行 BlueXP 分類先決條件指令碼

請依照下列步驟執行 BlueXP 分類先決條件指令碼。

https://youtu.be/5ONowfPWkFs?si=QLGUw8mqPrz9qs4B["觀看此影片"^]以瞭解如何執行 Prerequisites 指令碼並解譯結果。

.開始之前
* 驗證您的 Linux 系統是否符合<<驗證主機需求,主機需求>>。
* 確認系統已安裝兩個必要的軟體套件（ Docker Engine 或 Podman 和 Python 3 ）。
* 請確定您擁有Linux系統的root權限。


.步驟
. 從下載 BlueXP  分類先決條件指令碼 https://mysupport.netapp.com/site/products/all/details/cloud-data-sense/downloads-tab/["NetApp 支援網站"^]。您應該選擇的檔案名稱為 * 獨立式 - 必要的 - 測試者 - <version> * 。
. 將檔案複製到您打算使用的 Linux 主機（使用 `scp`或其他方法）。
. 指派執行指令碼的權限。
+
[source, cli]
----
chmod +x standalone-pre-requisite-tester-v1.25.0
----
. 使用下列命令執行指令碼。
+
[source, cli]
----
 ./standalone-pre-requisite-tester-v1.25.0 <--darksite>
----
+
只有在沒有網際網路存取權的主機上執行指令碼時、才新增選項「 ---變 暗站台」。當主機未連線至網際網路時、會略過某些必要測試。

. 指令碼會提示您輸入 BlueXP 分類主機的 IP 位址。
+
** 輸入 IP 位址或主機名稱。


. 指令碼會提示您是否已安裝 BlueXP Connector 。
+
** 如果您沒有安裝 Connector 、請輸入 * N* 。
** 如果您有安裝的 Connector 、請輸入 * Y* 。然後輸入 BlueXP Connector 的 IP 位址或主機名稱、讓測試指令碼可以測試這項連線功能。


. 指令碼會在系統上執行各種測試、並在執行過程中顯示結果。完成後，它會將工作階段記錄寫入目錄中的 `/opt/netapp/install_logs`檔案 `prerequisites-test-<timestamp>.log`。


.結果
如果所有先決條件測試都成功執行、您可以在準備就緒時、在主機上安裝 BlueXP 分類。

如果發現任何問題、則會將其歸類為「建議」或「必要」以進行修正。建議的問題通常是讓 BlueXP 分類掃描和分類工作執行速度變慢的項目。這些項目不需要修正、但您可能想解決這些問題。

如果您有任何「必要」問題、您應該修正這些問題、然後再次執行 Prerequisites 測試指令碼。
