---
sidebar: sidebar 
permalink: task-audit-data-sense-actions.html 
keywords: compliance, actions, view progress, audit, logs, installation 
summary: BlueXP 分類記錄在 BlueXP 分類所掃描的所有工作環境和資料來源檔案上執行的管理活動。BlueXP 分類也會記錄部署 BlueXP 分類執行個體時的活動。 
---
= 稽核 BlueXP 分類動作的歷史記錄
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP 分類記錄在 BlueXP 分類所掃描的所有工作環境和資料來源檔案上執行的管理活動。BlueXP 分類也會記錄部署 BlueXP 分類執行個體時的活動。

您可以檢視 BlueXP 分類稽核記錄檔的內容、或是下載這些檔案、查看發生了哪些檔案變更、以及何時發生變更。例如、您可以查看發出的要求、要求時間、以及檔案刪除時的來源位置、或檔案移動時的來源和目的地位置等詳細資料。

[]
====
* 注意 * 此資訊僅適用於 BlueXP 分類舊版 1.30 及更早版本。

====


== 記錄檔內容

稽核記錄中的每一行都包含下列格式的資訊：

`<full date> | <status> | ds_audit_logger | <module> | 0 | 0 | File <full file path> deleted from device <device path> - <result>`

* 日期與時間：事件的完整時間戳記
* 狀態-資訊、警告
* 行動類型（刪除、複製、移動、建立原則、更新原則、 重新掃描檔案、下載Json報告等）
* 檔案名稱（如果動作與檔案相關）
* 行動的詳細資料：做了什麼：取決於行動
+
** 原則名稱
** 用於移動-來源和目的地
** 複本：來源和目的地
** 用於標記-標記名稱
** 指派給-使用者名稱
** 電子郵件警示：電子郵件地址/帳戶




例如、記錄檔中的下列行顯示複製作業成功、複製作業失敗。

....
2022-06-06 15:23:08,910 | INFO | ds_audit_logger | es_scanned_file | 237 | 49 | Copy file /CIFS_share/data/dop1/random_positives.tsv from device 10.31.133.183 (type: SMB_SHARE) to device 10.31.130.133:/export_reports (NFS_SHARE) - SUCCESS
2022-06-06 15:23:08,968 | WARNING | ds_audit_logger | es_scanned_file | 239 | 153 | Copy file /CIFS_share/data/compliance-netapp.tar.gz from device 10.31.133.183 (type: SMB_SHARE) to device 10.31.130.133:/export_reports (NFS_SHARE) - FAILURE
....


== 記錄檔位置

管理稽核記錄檔位於以下位置的 BlueXP 分類機器： `/opt/netapp/audit_logs/`

安裝稽核記錄檔會寫入 `/opt/netapp/install_logs/`

每個記錄檔的大小上限為10 MB。達到該限制時、會啟動新的記錄檔。記錄檔的名稱為「DataSense_nap稽 核.log」、「DataSense_nap稽 核.log.1」、「DataSense_nap審查.log.2」等。系統上最多保留 100 個記錄檔 - 在達到最大值之後、會自動刪除較舊的記錄檔。



== 存取記錄檔

您必須登入 BlueXP 分類系統才能存取記錄檔。瞭解如何操作 link:reference-log-in-to-instance.html["登入 BlueXP 分類系統"] 視您是在 Linux 機器上手動安裝軟體、還是在雲端部署執行個體而定。
