---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, data sense, cloud data sense, bluexp, bluexp classification' 
summary: 瞭解 BlueXP 分類的新功能。 
---
= BlueXP  分類的新功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
瞭解 BlueXP 分類的新功能。



== 2025 年 12 月 5 日



=== 版本 1.43

此 BlueXP  分類版本包括：

.排定分類掃描的優先順序
BlueXP  分類可讓您在僅對應掃描之外，設定地圖和分類掃描的優先順序，讓您選擇先完成哪些掃描。在掃描開始期間和之前，都支援排列地圖和分類掃描的優先順序。如果您選擇在掃描進行期間排定優先順序，則對應和分類掃描都會排定優先順序。

如需更多資訊、請參閱 link:task-managing-repo-scanning.html#prioritize-scans["排定掃描的優先順序"]。

.支援加拿大個人識別資訊（ PII ）資料類別
BlueXP  分類掃描可識別加拿大 PII 資料類別，以取得所有省 / 地區的銀行資訊，護照號碼，社群保險號碼，以及駕照號碼和健康卡號碼。

如需更多詳細資訊xref:reference-private-data-categories.adoc#types-of-personal-data[個人資料類別]，請參閱。

.自訂分類（預覽）
BlueXP  分類可支援自訂的地圖分類和分類掃描。使用自訂分類，您可以量身打造 BlueXP  掃描，以擷取組織專屬的資料，確保符合規則運算式。此功能目前正在預覽中。

如需更多資訊、請參閱 xref:task-custom-classification.adoc[新增自訂分類]。

.儲存的搜尋索引標籤
**Policies ** 選項卡已重命名xref:task-using-policies.html[** 儲存的搜尋 **]。功能相同。

.將掃描事件傳送至 BlueXP  時間表
BlueXP  分類可支援傳送分類事件（當掃描開始及結束時）至link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#audit-user-activity-from-the-bluexp-timeline["BlueXP  時間表"^]。

.安全性更新
* Keras 套件已更新，可減輕資訊安全風險（ BDSA-2025-0107 和 BDSA-2025-1984 ）。
* Docker Container 組態已更新。容器不再能夠存取主機的網路介面來連接原始網路封包。透過減少不必要的存取，此更新可降低潛在的安全風險。


.效能增強
已實作程式碼增強功能，以減少 RAM 使用量，並改善 BlueXP  分類的整體效能。

.錯誤修正
導致 StorageGRID 掃描失敗的錯誤，無法載入調查頁面篩選選項，以及無法下載大量評估的資料探索評估已修正。



== 2025 年 4 月 14 日



=== 版本 1.42

此 BlueXP  分類版本包括：

.大量掃描工作環境
BlueXP  分類可支援工作環境的大量作業。您可以選擇啟用「對應掃描」，啟用「對應和分類掃描」，停用掃描，或在工作環境中跨磁碟區建立自訂組態。如果您為個別的 Volume 進行選擇，則會覆寫大量選擇。若要執行大量作業，請瀏覽至「 ** 組態 ** 」頁面並進行選擇。

.請在本機下載調查報告
BlueXP  分類可支援從本機下載資料調查報告，以便在瀏覽器中檢視。如果您選擇本機選項，則資料調查只能以 CSV 格式進行，而且只會顯示前 10 ， 000 列的資料。

如需更多資訊、請參閱 link:task-investigate-data.html#create-the-data-investigation-report["使用 BlueXP  分類來調查組織中儲存的資料"]。



== 2025 年 3 月 10 日



=== 版本 1.41

此 BlueXP  分類版本包含一般改良功能和錯誤修正。其中也包括：

.掃描狀態
BlueXP  分類可追蹤捲上 _initial_ 對應和分類掃描的即時進度。獨立的漸進式長條可追蹤對應和分類掃描，顯示掃描的檔案總數百分比。您也可以將游標暫留在進度列上，以檢視掃描的檔案數和檔案總數。追蹤掃描狀態可深入瞭解掃描進度，讓您更妥善地規劃掃描並瞭解資源分配。

若要檢視掃描的狀態，請瀏覽至 BlueXP  分類中的「 ** 組態 ** 」，然後選取「 ** 工作環境組態 ** 」。每個磁碟區的進度會以行顯示。



== 2025 年 19 月 2 日



=== 版本 1.40

此 BlueXP  分類版本包含下列更新。

.支援 RHEL 9.5
除了先前支援的版本之外、此版本還支援 Red Hat Enterprise Linux v9.5 。這適用於任何手動內部部署的 BlueXP  分類安裝、包括暗點部署。

下列作業系統需要使用 Podman Container 引擎，而且需要 BlueXP  分類 1.30 版或更新版本： Red Hat Enterprise Linux 8.8 ， 8.10 ， 9.0 ， 9.1 ， 9.2 ， 9.3 ， 9.4 和 9.5 版。

.排定僅對應掃描的優先順序
執行僅對應掃描時，您可以優先處理最重要的掃描。當您有許多工作環境，且想要確保先完成高優先順序掃描時，此功能會有所幫助。

依預設，掃描會根據其啟動順序排入佇列。有了優先處理掃描的能力，您就可以將掃描移到佇列的前方。可以優先處理多個掃描。優先順序是以先出的順序指定，也就是您優先處理的第一次掃描會移到佇列前方；您優先處理的第二次掃描會成為佇列中的第二次掃描，依此類推。

優先順序是一次性授予。自動重新掃描對應資料會依預設順序進行。

優先順序僅限於link:concept-cloud-compliance.html["僅對應掃描"]；不適用於地圖和分類掃描。

如需更多資訊、請參閱 link:task-managing-repo-scanning.html#prioritize-scans["排定掃描的優先順序"]。

.重試所有掃描
BlueXP  分類支援批次重試所有失敗掃描的功能。

您可以使用「 ** 全部重試」功能，在批次作業中重新嘗試掃描。如果分類掃描因網路中斷等暫時性問題而失敗，您可以使用單一按鈕同時重試所有掃描，而無需個別重試。掃描可視需要重試多次。

若要重試所有掃描：

. 從 BlueXP  分類功能表中，選取 * 組態 * 。
. 若要重試所有失敗的掃描，請選取 * 重試所有掃描 * 。


.改善分類模型準確度
的機器學習模型準確度link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-sensitive-personal-datapredefined-categories["預先定義的類別"]已提升 11% 。



== 2025 年 1 月 22 日



=== 版本 1.39

此 BlueXP  分類版本會更新資料調查報告的匯出程序。此匯出更新可用於對資料執行其他分析，在資料上建立其他視覺效果，或與他人分享資料調查結果。

以前，資料調查報告匯出限制為 10 ， 000 列。此版本已移除限制，您可以匯出所有資料。這項變更可讓您從資料調查報告匯出更多資料，讓您在資料分析時更有彈性。

您可以選擇工作環境，磁碟區，目的地資料夾，以及 JSON 或 CSV 格式。匯出的檔案名稱包含時間戳記，可協助您識別資料匯出的時間。

支援的工作環境包括：

* Cloud Volumes ONTAP
* FSX ONTAP
* ONTAP
* 共用群組


從「資料調查」報告匯出資料具有下列限制：

* 每種類型（檔案，目錄和表格）的最大記錄下載量為 5 億筆。
* 100 萬筆記錄預計需要 35 分鐘才能匯出。


如需資料調查與報告的詳細資訊，請參閱 https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["調查儲存在組織中的資料"]。



== 2024 年 16 月 12 日



=== 版本 1.38

此 BlueXP  分類版本包含一般改良功能和錯誤修正。



== 2024 年 4 月 11 日



=== 版本 1.37

此 BlueXP  分類版本包含下列更新。

.支援 RHEL 8.10
除了先前支援的版本之外、此版本還支援 Red Hat Enterprise Linux v8.10 。這適用於任何手動內部部署的 BlueXP  分類安裝、包括暗點部署。

下列作業系統需要使用 Podman Container 引擎、而且需要 BlueXP  分類 1.30 版或更新版本： Red Hat Enterprise Linux 8.8 、 8.10 、 9.0 、 9.1 、 9.2 、 9.3 和 9.4 版。

深入瞭解 https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["BlueXP 分類"]。

.支援 NFS v4.1
除了先前支援的版本之外、此版本也支援 NFS v4.1 。

深入瞭解 https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["BlueXP 分類"]。



== 2024 年 10 月 10 日



=== 版本 1.36

.支援 RHEL 9.4
除了先前支援的版本之外、此版本還支援 Red Hat Enterprise Linux v9.4 。這適用於任何手動內部部署的 BlueXP  分類安裝、包括暗點部署。

下列作業系統需要使用 Podman Container 引擎、而且需要 BlueXP  分類 1.30 版或更新版本： Red Hat Enterprise Linux 8.8 版、 9.0 版、 9.1 版、 9.2 版、 9.3 版和 9.4 版。

深入瞭解 https://docs.netapp.com/us-en/bluexp-classification/task-deploy-overview.html["BlueXP 分類部署總覽"]。

.改善掃描效能
此版本可改善掃描效能。



== 2024 年 9 月 2 日



=== 版本 1.35

.掃描 StorageGRID 資料
BlueXP  分類支援在 StorageGRID 中掃描資料。

如需詳細資訊、請 link:task-scanning-storagegrid.html["掃描 StorageGRID 資料"]參閱。



== 2024 年 8 月 5 日



=== 版本 1.34

此 BlueXP  分類版本包含下列更新。

.從 CentOS 變更為 Ubuntu
BlueXP  分類已將適用於 Microsoft Azure 和 Google Cloud Platform （ GCP ）的 Linux 作業系統從 CentOS 7.9 更新至 Ubuntu 22.04 。

如需部署詳細資料、請參閱 https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html#prepare-the-linux-host-system["在可存取網際網路的 Linux 主機上安裝、並準備 Linux 主機系統"]。



== 2024 年 7 月 1 日



=== 版本 1.33

.支援 Ubuntu
此版本支援 Ubuntu 24.04 Linux 平台。

.對應掃描會收集中繼資料
下列中繼資料會在對應掃描期間從檔案中擷取、並顯示在 Governance 、 Compliance 和 Investigation 儀表板上：

* 工作環境
* 工作環境類型
* 儲存儲存庫
* 檔案類型
* 已用容量
* 檔案數量
* 檔案大小
* 檔案建立
* 檔案上次存取
* 上次修改的檔案
* 檔案探索時間
* 權限擷取


.儀表板中的其他資料
此版本會在地圖繪製掃描期間、更新 Governance 、 Compliance 和 Investigation 儀表板中顯示的資料。

如需詳細資訊、請參閱 link:https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["對應和分類掃描之間有何差異"]。



== 2024 年 5 月 6 日



=== 版本 1.32

.「組態」頁面中的「新對應」狀態欄
此版本現在會在「組態」頁面中顯示新的「對應」狀態欄。新欄可協助您識別對應是否正在執行、佇列中、暫停或更多。

有關狀態的說明，請參閱 https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html["變更掃描設定"]。



== 2024 年 5 月 15 日



=== 版本 1.31

.分類可在 BlueXP 中作為核心服務使用
BlueXP 分類現在可在 BlueXP 中作為核心功能使用、最多可免費取得 500 TiB 的掃描資料。不需要分類授權或付費訂閱。由於 BlueXP 分類功能著重於使用此新版本掃描 NetApp 儲存系統、因此部分舊版功能僅適用於先前已支付授權費用的客戶。這些舊版功能的使用將在已支付合約到期時到期。

link:reference-free-paid.html["深入瞭解過時的功能"]。



== 2024 年 4 月 1 日



=== 版本 1.30

.新增 RHEL v8.8 和 v9.3 BlueXP 分類支援
此版本除了先前支援的 9.x 以外、也支援 Red Hat Enterprise Linux v8.8 和 v9.3 、這需要 Podman 、而非 Docker 引擎。這適用於 BlueXP 分類的任何內部部署手動安裝。

下列作業系統需要使用 Podman Container 引擎、而且需要 BlueXP 分類版本 1.30 或更新版本： Red Hat Enterprise Linux 版本 8.8 、 9.0 、 9.1 、 9.2 及 9.3 。

深入瞭解 https://docs.netapp.com/us-en/bluexp-classification/task-deploy-overview.html["BlueXP 分類部署總覽"]。

如果您在內部部署的 RHEL 8 或 9 主機上安裝 Connector 、則支援 BlueXP 分類。如果 RHEL 8 或 9 主機位於 AWS 、 Azure 或 Google Cloud 、則不支援此功能。

.選項可啟動已移除的稽核記錄集合
啟用稽核記錄集合的選項已停用。

.掃描速度更快
二次掃描儀節點上的掃描效能已改善。如果您需要額外的處理能力來進行掃描、您可以新增更多掃描器節點。如需詳細資訊、請 https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["在可存取網際網路的主機上安裝 BlueXP 分類"]參閱。

.自動升級
如果您在可存取網際網路的系統上部署 BlueXP 分類、系統會自動升級。之前、升級是在上次使用者活動之後經過一段特定時間之後進行。在此版本中，如果當地時間介於上午 1 ： 00 至上午 5 ： 00 之間， BlueXP  分類會自動升級。如果本地時間超出這些時間、則升級會在上次使用者活動之後經過一段特定時間後進行。如需詳細資訊、請 https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["安裝在可存取網際網路的Linux主機上"]參閱。

如果您部署的 BlueXP 分類沒有網際網路存取、則需要手動升級。如需詳細資訊、請 https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-dark-site.html["在無法存取網際網路的 Linux 主機上安裝 BlueXP 分類"]參閱。



== 2024 年 3 月 4 日



=== 版本 1.29

.現在您可以排除位於特定資料來源目錄中的掃描資料
如果您想要 BlueXP 分類排除位於特定資料來源目錄中的掃描資料、您可以將這些目錄名稱新增至 BlueXP 分類處理的組態檔。此功能可讓您避免掃描不必要的目錄、或是導致傳回誤判的個人資料結果。

https://docs.netapp.com/us-en/bluexp-classification/task-exclude-scan-paths.html["深入瞭解"]。

.超大型執行個體支援現已符合資格
如果您需要 BlueXP 分類來掃描超過 2.5 億個檔案、您可以在雲端部署或內部部署安裝中使用超大型執行個體。這類系統最多可掃描 5 億個檔案。

https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html#using-a-smaller-instance-type["深入瞭解"]。



== 2024 年 1 月 10 日



=== 版本 1.27

.調查頁面結果除了顯示項目總數之外，還會顯示總大小
「調查」頁面中的篩選結果除了顯示檔案總數之外，還會顯示項目的總大小。這有助於移動檔案、刪除檔案等。

.將其他群組 ID 設定為「開放給組織」
現在您可以在 NFS 中設定群組 ID 、以便直接從 BlueXP 分類中將其視為「開放組織」、如果群組一開始沒有設定該權限。任何附加這些群組 ID 的檔案和資料夾、都會在「調查詳細資料」頁面中顯示為「開放給組織」。請參閱如何 https://docs.netapp.com/us-en/bluexp-classification/task-add-group-id-as-open.html["新增其他群組 ID 為「開放給組織」"]。



== 2023 年 14 月 12 日



=== 版本 1.26.6

此版本包含一些小的增強功能。

此版本也移除下列選項：

* 啟用稽核記錄集合的選項已停用。
* 在目錄調查期間，無法使用依目錄計算個人識別資訊（ PII ）資料數量的選項。請參閱 link:task-investigate-data.html["調查組織中儲存的資料"]。
* 已停用使用 Azure Information Protection （ AIP ）標籤整合資料的選項。請參閱 link:task-org-private-data.html["組織您的私有資料"]。




== 2023 年 6 月 11 日



=== 版本 1.26.3

本版本已修正下列問題

* 修正在儀表板中顯示系統掃描的檔案數量時出現不一致的情況。
* 處理和報告名稱和中繼資料中含有特殊字元的檔案和目錄、以改善掃描行為。




== 2023 年 4 月 10 日



=== 版本 1.26

.支援在 RHEL 第 9 版上內部部署安裝 BlueXP 分類
Red Hat Enterprise Linux 第 8 版和第 9 版不支援 Docker 引擎、這是 BlueXP 分類安裝所需的。我們現在支援在 RHEL 9.0 、 9.1 和 9.2 上安裝 BlueXP 分類、並使用 Podman 版本 4 或更新版本做為容器基礎架構。如果您的環境需要使用最新版本的 RHEL 、現在您可以在使用 Podman 時安裝 BlueXP 分類（ 1.26 版或更新版本）。

目前、我們不支援使用 RHEL 9.x 進行暗點安裝或分散式掃描環境（使用主要和遠端掃描器節點）



== 2023 年 9 月 5 日



=== 版本 1.25

.中小企業部署暫時無法使用
當您在 AWS 中部署 BlueXP 分類執行個體時、目前無法使用選擇 * 部署 > 組態 * 並選擇中小型執行個體的選項。您仍然可以使用大型執行個體來部署執行個體、方法是選取 * 部署 > 部署 * 。

.從「調查結果」頁面、最多可在 100 、 000 個項目上套用標記
過去、您只能在「調查結果」頁面（ 20 個項目）中一次將標記套用至單一頁面。現在您可以在「調查結果」頁面中選取 * 所有 * 項目，並將標記套用至所有項目，一次最多可有 100,000 個項目。 https://docs.netapp.com/us-en/bluexp-classification/task-org-private-data.html#assign-tags-to-files["瞭解方法"]。

.識別檔案大小最小為 1 MB 的重複檔案
BlueXP 分類僅在檔案大小為 50 MB 時用於識別重複的檔案。現在可以識別以 1 MB 開始的重複檔案。您可以使用「調查」頁面篩選「檔案大小」和「重複」、來查看環境中有哪些檔案大小的複本。



== 2023 年 7 月 17 日



=== 版本 1.24

.BlueXP 分類可識別兩種新類型的德國個人資料
BlueXP 分類可識別及分類包含下列資料類型的檔案：

* 德文 ID （ Personalausweisnummer ）
* 德國社會安全號碼（ Szialversicherungsnummer ）


https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["查看 BlueXP 分類可在資料中識別的所有個人資料類型"]。

.在受限模式和私有模式下、完全支援 BlueXP 分類
BlueXP  分類現在已在沒有網際網路存取（私有模式）且輸出網際網路存取有限（限制模式）的網站中獲得完整支援。 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["深入瞭解 Connector 的 BlueXP 部署模式"^]。

.在升級 BlueXP 分類的私有模式安裝時、可以略過版本
現在您可以升級至較新版本的 BlueXP 分類、即使它不是連續的。這表示目前不再需要將 BlueXP 分類一次升級一個版本的限制。從 1.24 版開始、此功能相當實用。

.BlueXP 分類 API 現已推出
BlueXP 分類 API 可讓您執行動作、建立查詢、以及匯出所掃描資料的相關資訊。可使用 Swagger 取得互動式文件。文件分為多個類別、包括調查、法規遵循、治理和組態。每個類別都是 BlueXP 分類 UI 中標籤的參考資料。

https://docs.netapp.com/us-en/bluexp-classification/api-classification.html["深入瞭解 BlueXP 分類 API"]。



== 2023 年 6 月 6 日



=== 版本 1.23

.搜尋資料主體名稱時、現在支援日文
現在可以在搜尋受試者名稱以回應資料主體存取要求（ DSAR ）時輸入日文名稱。您可以使用產生的資訊來產生 https://docs.netapp.com/us-en/bluexp-classification/task-generating-compliance-reports.html["資料主旨存取要求報告"]。您也可以在中輸入日文名稱 https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["「資料調查」頁面中的「資料主旨」篩選器"]，以識別包含主旨名稱的檔案。

.Ubuntu 現在是支援的 Linux 套裝作業系統、您可以在其中安裝 BlueXP 分類
Ubuntu 22.04 已獲認證為 BlueXP 分類支援的作業系統。使用 1.23 版安裝程式時，您可以在網路中的 Ubuntu Linux 主機或雲端中的 Linux 主機上安裝 BlueXP  分類。 https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["瞭解如何在安裝 Ubuntu 的主機上安裝 BlueXP 分類"]。

.新的 BlueXP 分類安裝不再支援 Red Hat Enterprise Linux 8.6 和 8.7
新部署不支援這些版本、因為 Red Hat 不再支援 Docker 、這是必要條件。如果您現有的 BlueXP 分類機器在 RHEL 8.6 或 8.7 上執行、 NetApp 將繼續支援您的組態。

.BlueXP 分類可設定為 FPolicy 收集器、以從 ONTAP 系統接收 FPolicy 事件
您可以啟用在 BlueXP 分類系統上收集檔案存取稽核記錄、以便在工作環境中的磁碟區上偵測到檔案存取事件。BlueXP 分類可擷取下列類型的 FPolicy 事件、以及對檔案執行動作的使用者：建立、讀取、寫入、刪除、重新命名、 變更擁有者 / 權限、並變更 SACL/DACL 。

.Data Sense BYOL 授權現在支援 Dark 站台
現在您可以將 Data Sense BYOL 授權上傳至黑暗網站的 BlueXP 數位錢包、以便在授權即將到期時收到通知。



== 2023 年 4 月 3 日



=== 版本 1.22

.新的資料探索評估報告
「資料探索評估報告」會針對您所掃描的環境提供高層級分析、以強調系統的發現、並顯示關切領域和可能的補救步驟。本報告的目標是提高對資料治理疑慮，資料安全性曝露及資料集資料合規性缺口的認知度。 https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html["瞭解如何產生及使用資料探索評估報告"]。

.能夠在雲端的較小執行個體上部署 BlueXP 分類
在 AWS 環境中從 BlueXP Connector 部署 BlueXP 分類時、現在您可以從兩種比預設執行個體可用的執行個體類型更小的執行個體類型中進行選擇。如果您掃描的是小型環境、這有助於節省雲端成本。不過，使用較小的執行個體時會有一些限制。 https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["請參閱可用的執行個體類型和限制"]。

.獨立指令碼現已推出、可在安裝 BlueXP 分類之前驗證您的 Linux 系統
如果您想驗證 Linux 系統是否符合所有先決條件，而不需執行 BlueXP  分類安裝，您可以下載一個獨立的指令碼，只測試先決條件。 https://docs.netapp.com/us-en/bluexp-classification/task-test-linux-system.html["瞭解如何檢查您的 Linux 主機是否已準備好安裝 BlueXP 分類"]。



== 2023 年 3 月 7 日



=== 版本 1.21

.新功能可從 BlueXP 分類 UI 新增您自己的自訂類別
BlueXP 分類現在可讓您新增自己的自訂類別、以便 BlueXP 分類能識別符合這些類別的檔案。BlueXP  分類有許多 https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html["預先定義的類別"]種，因此此功能可讓您新增自訂類別，以識別組織特有的資訊在資料中的位置。

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html["深入瞭解"^]。

.現在您可以從 BlueXP 分類 UI 新增自訂關鍵字
BlueXP 分類已能夠新增自訂關鍵字、 BlueXP 分類將在未來的掃描中識別這些關鍵字。不過、您需要登入 BlueXP 分類 Linux 主機、並使用命令列介面來新增關鍵字。在此版本中、新增自訂關鍵字的功能位於 BlueXP 分類 UI 中、因此很容易新增及編輯這些關鍵字。

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html["深入瞭解如何從 BlueXP 分類 UI 新增自訂關鍵字"^]。

.在「上次存取時間」變更時、能夠將 BlueXP 分類 * 非 * 掃描檔案
根據預設、如果 BlueXP 分類沒有足夠的「寫入」權限、系統將不會掃描您磁碟區中的檔案、因為 BlueXP 分類無法將「上次存取時間」還原為原始時間戳記。不過、如果您不介意上次存取時間重設為檔案中的原始時間、您可以在「組態」頁面中覆寫此行為、以便 BlueXP 分類不論權限為何、都能掃描磁碟區。

結合這項功能、新增了名為「掃描分析事件」的篩選器、讓您可以檢視未分類的檔案、因為 BlueXP 分類無法還原上次存取的時間、或是即使 BlueXP 分類無法還原上次存取的時間、也無法還原已分類的檔案。

https://docs.netapp.com/us-en/bluexp-classification/reference-collected-metadata.html["深入瞭解「上次存取時間戳記」和 BlueXP 分類所需的權限"]。

.BlueXP 分類可識別三種新的個人資料類型
BlueXP 分類可識別及分類包含下列資料類型的檔案：

* 波札那身分證（Omang）號碼
* 波札那護照號碼
* 新加坡國家註冊身分證（NRIC）


https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html["查看 BlueXP 分類可在資料中識別的所有個人資料類型"]。

.目錄的更新功能
* 資料調查報告的「輕度CSV報告」選項現在包含來自目錄的資訊。
* 「上次存取」時間篩選器現在會顯示檔案和目錄的上次存取時間。


.安裝增強功能
* 對於無法存取網際網路的網站（黑暗網站）、 BlueXP 分類安裝程式現在會執行預先檢查、以確保您的系統和網路需求已就緒、以便順利安裝。
* 安裝稽核記錄檔會立即儲存；這些檔案會寫入 `/ops/netapp/install_logs`。




== 2023 年 2 月 5 日



=== 版本 1.20

.能夠將原則型通知電子郵件傳送至任何電子郵件地址
在 BlueXP 分類的舊版中、當某些關鍵原則傳回結果時、您可以傳送電子郵件警示給帳戶中的 BlueXP 使用者。此功能可讓您取得通知、在您不在線上時保護資料。現在、您也可以將原則的電子郵件警示傳送給任何其他使用者（最多20個電子郵件地址）、而這些使用者不在您的BlueXP帳戶中。

https://docs.netapp.com/us-en/bluexp-classification/task-using-policies.html["深入瞭解如何根據原則結果傳送電子郵件警示"]。

.現在您可以從 BlueXP 分類 UI 新增個人模式
BlueXP 分類已能夠新增自訂的「個人資料」、 BlueXP 分類將在未來的掃描中識別這些資料。不過、您需要登入 BlueXP 分類 Linux 主機、並使用命令列來新增自訂模式。在此版本中、使用 regex 新增個人模式的功能位於 BlueXP 分類 UI 中、因此新增及編輯這些自訂模式非常容易。

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html["深入瞭解如何從 BlueXP 分類 UI 新增自訂模式"^]。

.能夠使用 BlueXP 分類來移動 1500 萬個檔案
過去、 BlueXP 分類最多可將 100 、 000 個來源檔案移至任何 NFS 共用區。現在您一次最多可以移動 1500 萬個檔案。 https://docs.netapp.com/us-en/bluexp-classification/task-managing-highlights.html["深入瞭解如何使用 BlueXP 分類來移動來源檔案"]。

.能夠查看有權存取SharePoint Online檔案的使用者人數
篩選器「具有存取權限的使用者人數」現在支援儲存在SharePoint Online儲存庫中的檔案。過去只支援CIFS共用上的檔案。請注意、目前不以Active Directory為基礎的SharePoint群組將不會計入此篩選器。

.新的「部分成功」狀態已新增至「行動狀態」面板
新的「部分成功」狀態表示 BlueXP 分類動作已完成、有些項目失敗、有些項目成功、例如當您移動或刪除 100 個檔案時。此外、「已完成」狀態已重新命名為「成功」。過去、「已完成」狀態可能會列出成功及失敗的動作。現在「成功」狀態表示所有項目的所有動作都成功。 https://docs.netapp.com/us-en/bluexp-classification/task-view-compliance-actions.html["請參閱如何檢視「動作狀態」面板"]。



== 2023 年 1 月 9 日



=== 版本 1.19

.能夠檢視含有敏感資料且過於許可的檔案圖表
「治理」儀表板新增了「敏感資料」和「廣泛權限」區域、提供內含敏感資料（包括敏感和敏感個人資料）且過於許可的檔案熱圖。這有助於您瞭解敏感資料可能會有哪些風險。 https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html["深入瞭解"]。

.「資料調查」頁面提供三種新篩選條件
我們提供新的篩選條件、以精簡「資料調查」頁面中顯示的結果：

* 「有存取權的使用者人數」篩選器會顯示哪些檔案和資料夾已對特定數量的使用者開放。您可以選擇一個數字範圍來精簡結果、例如、查看51到100位使用者可以存取哪些檔案。
* 「建立時間」、「探索時間」、「上次修改時間」和「上次存取時間」篩選條件現在可讓您建立自訂日期範圍、而不只是選擇預先定義的天數範圍。例如、您可以在「過去10天」內尋找「建立時間」為「6個月以上」或「上次修改日期」的檔案。
* 「檔案路徑」篩選現在可讓您指定要從篩選查詢結果中排除的路徑。如果您輸入包含和排除某些資料的路徑、 BlueXP 分類會先尋找包含路徑中的所有檔案、然後從排除路徑中移除檔案、然後顯示結果。


https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["請參閱所有篩選器清單、以供您調查資料"]。

.BlueXP 分類可識別日本個人號碼
BlueXP 分類可識別及分類包含日文個人編號（也稱為「我的號碼」）的檔案。這包括「個人」和「公司我的號碼」。 https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html["查看 BlueXP 分類可在資料中識別的所有個人資料類型"]。
