---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, data sense' 
summary: 瞭解 BlueXP 分類的新功能。 
---
= BlueXP 分類的新功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
瞭解 BlueXP 分類的新功能。



== 10 月 4 日（版本 1.26 ）



=== 支援在 RHEL 第 9 版上內部部署安裝 BlueXP 分類

Red Hat Enterprise Linux 第 8 版和第 9 版不支援 Docker 引擎、這是 BlueXP 分類安裝所需的。我們現在支援在 RHEL 9.0 、 9.1 和 9.2 上安裝 BlueXP 分類、並使用 Podman 版本 4 或更新版本做為容器基礎架構。如果您的環境需要使用最新版本的 RHEL 、現在您可以在使用 Podman 時安裝 BlueXP 分類（ 1.26 版或更新版本）。

目前、我們不支援使用 RHEL 9.x 進行暗點安裝或分散式掃描環境（使用主要和遠端掃描器節點）



== 9 月 5 日（ 1.25 版）



=== 中小企業部署暫時無法使用

當您在 AWS 中部署 BlueXP 分類執行個體時、目前無法使用選擇 * 部署 > 組態 * 並選擇中小型執行個體的選項。您仍然可以使用大型執行個體來部署執行個體、方法是選取 * 部署 > 部署 * 。



=== 從「調查結果」頁面、最多可在 100 、 000 個項目上套用標記

過去、您只能在「調查結果」頁面（ 20 個項目）中一次將標記套用至單一頁面。現在您可以在「調查結果」頁面中選取 * 所有 * 項目、並將標記套用至所有項目、一次最多可有 100,000 個項目。 https://docs.netapp.com/us-en/bluexp-classification/task-org-private-data.html#assigning-tags-to-files["瞭解方法"]。



=== 識別檔案大小最小為 1 MB 的重複檔案

BlueXP 分類僅在檔案大小為 50 MB 時用於識別重複的檔案。現在可以識別以 1 MB 開始的重複檔案。您可以使用「調查」頁面篩選「檔案大小」和「重複」、來查看環境中有哪些檔案大小的複本。



== 2023 年 7 月 17 日（版本 1.24 ）



=== BlueXP 分類可識別兩種新類型的德國個人資料

BlueXP 分類可識別及分類包含下列資料類型的檔案：

* 德文 ID （ Personalausweisnummer ）
* 德國社會安全號碼（ Szialversicherungsnummer ）


https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["查看 BlueXP 分類可在資料中識別的所有個人資料類型"]。



=== 在受限模式和私有模式下、完全支援 BlueXP 分類

BlueXP 分類現在已在沒有網際網路存取（私有模式）和限制外傳網際網路存取（限制模式）的網站中獲得完整支援。 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["深入瞭解 Connector 的 BlueXP 部署模式"^]。



=== 在升級 BlueXP 分類的私有模式安裝時、可以略過版本

現在您可以升級至較新版本的 BlueXP 分類、即使它不是連續的。這表示目前不再需要將 BlueXP 分類一次升級一個版本的限制。從 1.24 版開始、此功能相當實用。



=== BlueXP 分類 API 現已推出

BlueXP 分類 API 可讓您執行動作、建立查詢、以及匯出所掃描資料的相關資訊。可使用 Swagger 取得互動式文件。文件分為多個類別、包括調查、法規遵循、治理和組態。每個類別都是 BlueXP 分類 UI 中標籤的參考資料。

https://docs.netapp.com/us-en/bluexp-classification/api-classification.html["深入瞭解 BlueXP 分類 API"]。



== 2023 年 6 月 6 日（版本 1.23 ）



=== 搜尋資料主體名稱時、現在支援日文

現在可以在搜尋受試者名稱以回應資料主體存取要求（ DSAR ）時輸入日文名稱。您可以產生 https://docs.netapp.com/us-en/bluexp-classification/task-generating-compliance-reports.html#what-is-a-data-subject-access-request["資料主旨存取要求報告"] 以及產生的資訊。您也可以在中輸入日文名稱 https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html#filter-data-by-sensitivity-and-content["「資料調查」頁面中的「資料主旨」篩選器"] 識別包含主體名稱的檔案。



=== Ubuntu 現在是支援的 Linux 套裝作業系統、您可以在其中安裝 BlueXP 分類

Ubuntu 22.04 已獲認證為 BlueXP 分類支援的作業系統。您可以在網路中的 Ubuntu Linux 主機上安裝 BlueXP 分類、或在雲端的 Linux 主機上使用 1.23 版的安裝程式。 https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["瞭解如何在安裝 Ubuntu 的主機上安裝 BlueXP 分類"]。



=== 新的 BlueXP 分類安裝不再支援 Red Hat Enterprise Linux 8.6 和 8.7

新部署不支援這些版本、因為 Red Hat 不再支援 Docker 、這是必要條件。如果您現有的 BlueXP 分類機器在 RHEL 8.6 或 8.7 上執行、 NetApp 將繼續支援您的組態。



=== BlueXP 分類可設定為 FPolicy 收集器、以從 ONTAP 系統接收 FPolicy 事件

您可以啟用在 BlueXP 分類系統上收集檔案存取稽核記錄、以便在工作環境中的磁碟區上偵測到檔案存取事件。BlueXP 分類可擷取下列類型的 FPolicy 事件、以及對檔案執行動作的使用者：建立、讀取、寫入、刪除、重新命名、 變更擁有者 / 權限、並變更 SACL/DACL 。 https://docs.netapp.com/us-en/bluexp-classification/task-manage-file-access-events.html["瞭解如何監控及管理檔案存取事件"]。



=== Data Sense BYOL 授權現在支援 Dark 站台

現在您可以將 Data Sense BYOL 授權上傳至黑暗網站的 BlueXP 數位錢包、以便在授權即將到期時收到通知。 https://docs.netapp.com/us-en/bluexp-classification/task-licensing-datasense.html#obtain-your-bluexp-classification-license-file["瞭解如何取得及上傳您的 Data Sense BYOL 授權"]。



== 2023 年 4 月 3 日（版本 1.22 ）



=== 新的資料探索評估報告

「資料探索評估報告」會針對您所掃描的環境提供高層級分析、以強調系統的發現、並顯示關切領域和可能的補救步驟。本報告的目標是提高對資料治理疑慮、資料安全性曝露及資料集資料合規性缺口的認知度。 https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html#data-discovery-assessment-report["瞭解如何產生及使用資料探索評估報告"]。



=== 能夠在雲端的較小執行個體上部署 BlueXP 分類

在 AWS 環境中從 BlueXP Connector 部署 BlueXP 分類時、現在您可以從兩種比預設執行個體可用的執行個體類型更小的執行個體類型中進行選擇。如果您掃描的是小型環境、這有助於節省雲端成本。不過、使用較小的執行個體時會有一些限制。 https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html#using-a-smaller-instance-type["請參閱可用的執行個體類型和限制"]。



=== 獨立指令碼現已推出、可在安裝 BlueXP 分類之前驗證您的 Linux 系統

如果您想驗證 Linux 系統是否符合所有先決條件、而不需執行 BlueXP 分類安裝、您可以下載一個獨立的指令碼、只測試先決條件。 https://docs.netapp.com/us-en/bluexp-classification/task-test-linux-system.html["瞭解如何檢查您的 Linux 主機是否已準備好安裝 BlueXP 分類"]。



== 2023年3月7日（版本1.21）



=== 新功能可從 BlueXP 分類 UI 新增您自己的自訂類別

BlueXP 分類現在可讓您新增自己的自訂類別、以便 BlueXP 分類能識別符合這些類別的檔案。BlueXP 分類有許多 https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-categories["預先定義的類別"]因此，此功能可讓您新增自訂類別，以識別在資料中找到組織專屬的資訊。

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html#add-custom-categories["深入瞭解"^]。



=== 現在您可以從 BlueXP 分類 UI 新增自訂關鍵字

BlueXP 分類已能夠新增自訂關鍵字、 BlueXP 分類將在未來的掃描中識別這些關鍵字。不過、您需要登入 BlueXP 分類 Linux 主機、並使用命令列介面來新增關鍵字。在此版本中、新增自訂關鍵字的功能位於 BlueXP 分類 UI 中、因此很容易新增及編輯這些關鍵字。

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html#add-custom-keywords-from-a-list-of-words["深入瞭解如何從 BlueXP 分類 UI 新增自訂關鍵字"^]。



=== 在「上次存取時間」變更時、能夠將 BlueXP 分類 * 非 * 掃描檔案

根據預設、如果 BlueXP 分類沒有足夠的「寫入」權限、系統將不會掃描您磁碟區中的檔案、因為 BlueXP 分類無法將「上次存取時間」還原為原始時間戳記。不過、如果您不介意上次存取時間重設為檔案中的原始時間、您可以在「組態」頁面中覆寫此行為、以便 BlueXP 分類不論權限為何、都能掃描磁碟區。

結合這項功能、新增了名為「掃描分析事件」的篩選器、讓您可以檢視未分類的檔案、因為 BlueXP 分類無法還原上次存取的時間、或是即使 BlueXP 分類無法還原上次存取的時間、也無法還原已分類的檔案。

https://docs.netapp.com/us-en/bluexp-classification/reference-collected-metadata.html#last-access-time-timestamp["深入瞭解「上次存取時間戳記」和 BlueXP 分類所需的權限"]。



=== BlueXP 分類可識別三種新的個人資料類型

BlueXP 分類可識別及分類包含下列資料類型的檔案：

* 波札那身分證（Omang）號碼
* 波札那護照號碼
* 新加坡國家註冊身分證（NRIC）


https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["查看 BlueXP 分類可在資料中識別的所有個人資料類型"]。



=== 目錄的更新功能

* 資料調查報告的「輕度CSV報告」選項現在包含來自目錄的資訊。
* 「上次存取」時間篩選器現在會顯示檔案和目錄的上次存取時間。




=== 安裝增強功能

* 對於無法存取網際網路的網站（黑暗網站）、 BlueXP 分類安裝程式現在會執行預先檢查、以確保您的系統和網路需求已就緒、以便順利安裝。
* 安裝稽核記錄檔現在會儲存、並寫入 `/ops/netapp/install_logs`。




== 2023年2月5日（1.20版）



=== 能夠將原則型通知電子郵件傳送至任何電子郵件地址

在 BlueXP 分類的舊版中、當某些關鍵原則傳回結果時、您可以傳送電子郵件警示給帳戶中的 BlueXP 使用者。此功能可讓您取得通知、在您不在線上時保護資料。現在、您也可以將原則的電子郵件警示傳送給任何其他使用者（最多20個電子郵件地址）、而這些使用者不在您的BlueXP帳戶中。

https://docs.netapp.com/us-en/bluexp-classification/task-using-policies.html#sending-email-alerts-when-non-compliant-data-is-found["深入瞭解如何根據原則結果傳送電子郵件警示"]。



=== 現在您可以從 BlueXP 分類 UI 新增個人模式

BlueXP 分類已能夠新增自訂的「個人資料」、 BlueXP 分類將在未來的掃描中識別這些資料。不過、您需要登入 BlueXP 分類 Linux 主機、並使用命令列來新增自訂模式。在此版本中、使用 regex 新增個人模式的功能位於 BlueXP 分類 UI 中、因此新增及編輯這些自訂模式非常容易。

https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html#add-custom-personal-data-identifiers-using-a-regex["深入瞭解如何從 BlueXP 分類 UI 新增自訂模式"^]。



=== 能夠使用 BlueXP 分類來移動 1500 萬個檔案

過去、 BlueXP 分類最多可將 100 、 000 個來源檔案移至任何 NFS 共用區。現在您一次最多可以搬移1500萬個檔案。 https://docs.netapp.com/us-en/bluexp-classification/task-managing-highlights.html#moving-source-files-to-an-nfs-share["深入瞭解如何使用 BlueXP 分類來移動來源檔案"]。



=== 能夠查看有權存取SharePoint Online檔案的使用者人數

篩選器「具有存取權限的使用者人數」現在支援儲存在SharePoint Online儲存庫中的檔案。過去只支援CIFS共用上的檔案。請注意、目前不以Active Directory為基礎的SharePoint群組將不會計入此篩選器。



=== 新的「部分成功」狀態已新增至「行動狀態」面板

新的「部分成功」狀態表示 BlueXP 分類動作已完成、有些項目失敗、有些項目成功、例如當您移動或刪除 100 個檔案時。此外、「已完成」狀態已重新命名為「成功」。過去、「已完成」狀態可能會列出成功及失敗的動作。現在「成功」狀態代表所有項目的所有行動都成功。 https://docs.netapp.com/us-en/bluexp-classification/task-view-compliance-actions.html["請參閱如何檢視「動作狀態」面板"]。



== 2023年1月9日（1.19版）



=== 能夠檢視含有敏感資料且過於許可的檔案圖表

「治理」儀表板新增了「敏感資料」和「廣泛權限」區域、提供內含敏感資料（包括敏感和敏感個人資料）且過於許可的檔案熱圖。這有助於您瞭解敏感資料的風險所在。 https://docs.netapp.com/us-en/bluexp-classification/task-controlling-governance-data.html#data-listed-by-sensitivity-and-wide-permissions["深入瞭解"]。



=== 「資料調查」頁面提供三種新篩選條件

我們提供新的篩選條件、以精簡「資料調查」頁面中顯示的結果：

* 「有存取權的使用者人數」篩選器會顯示哪些檔案和資料夾已對特定數量的使用者開放。您可以選擇一個數字範圍來精簡結果、例如、查看51到100位使用者可以存取哪些檔案。
* 「建立時間」、「探索時間」、「上次修改時間」和「上次存取時間」篩選條件現在可讓您建立自訂日期範圍、而不只是選擇預先定義的天數範圍。例如、您可以在「過去10天」內尋找「建立時間」為「6個月以上」或「上次修改日期」的檔案。
* 「檔案路徑」篩選現在可讓您指定要從篩選查詢結果中排除的路徑。如果您輸入包含和排除某些資料的路徑、 BlueXP 分類會先尋找包含路徑中的所有檔案、然後從排除路徑中移除檔案、然後顯示結果。


https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html#filtering-data-in-the-data-investigation-page["請參閱所有篩選器清單、以供您調查資料"]。



=== BlueXP 分類可識別日本個人號碼

BlueXP 分類可識別及分類包含日文個人編號（也稱為「我的號碼」）的檔案。這包括「個人」和「公司我的號碼」。 https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-personal-data["查看 BlueXP 分類可在資料中識別的所有個人資料類型"]。



== 2022年12月11日（版本1.18）



=== 內部部署安裝增強功能

內部部署Data Sense安裝新增下列增強功能：

* 在內部部署主機上開始安裝之前、現在會先檢查其他一些先決條件。這有助於確保主機系統100%準備好安裝Data Sense軟體：
+
** 測試上是否有足夠的空間 `/var/lib/docker`、 `/tmp`和 `/opt`
** 測試所有必要資料夾的相關權限


* 在「組態」頁面中、「工作環境」區段現在會顯示_工作環境ID_和_掃描器群組_名稱。如果您打算使用多個Data Sense主機來提供額外的處理能力來掃描資料來源、則必須知道工作環境ID。
* 此外、在「組態」頁面中、會有一個新區段顯示您已設定的掃描器群組、以及每個群組中的掃描器節點。


https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html["深入瞭解如何在單一主機伺服器和多個主機上安裝Data Sense"]。



== 2022年11月13日（1.17版）



=== 支援掃描SharePoint內部部署帳戶

Data Sense現在可以掃描SharePoint Online帳戶和SharePoint內部部署帳戶（SharePoint Server）。如果您需要在自己的伺服器上安裝SharePoint、或是在無法存取網際網路的站台上安裝SharePoint、現在您可以讓Data Sense掃描這些帳戶中的使用者檔案。 https://docs.netapp.com/us-en/bluexp-classification/task-scanning-sharepoint.html#adding-a-sharepoint-on-premise-account["深入瞭解"^]。



=== 能夠重新掃描多個目錄（資料夾或共用）

現在、您可以立即重新掃描多個目錄（資料夾或共用）、使變更反映在系統中。這可讓您優先重新掃描特定資料、然後再處理其他資料。 https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#rescanning-data-for-an-existing-repository["請參閱如何重新掃描目錄"^]。



=== 能夠新增額外的內部部署「掃描器」節點、以掃描特定的資料來源

如果您已在內部部署位置安裝Data Sense、而且發現掃描特定資料來源需要更多掃描處理能力、您可以新增更多「掃描」節點、並指派它們來掃描這些資料來源。您可以在安裝管理節點之後立即新增掃描儀節點、也可以稍後新增掃描儀節點。

如有必要、可將掃描器節點安裝在實體靠近您要掃描之資料來源的主機系統上。掃描儀節點越靠近資料、越好、因為掃描資料時會盡可能減少網路延遲。 https://docs.netapp.com/us-en/bluexp-classification/task-deploy-compliance-onprem.html#add-scanner-nodes-to-an-existing-deployment["瞭解如何安裝掃描器節點來掃描其他資料來源"^]。



=== 內部部署安裝程式現在會在開始安裝之前執行預先檢查

在Linux系統上安裝Data Sense時、安裝程式會先檢查系統是否符合所有必要的需求（CPU、RAM、容量、網路等）、然後再開始實際安裝。這有助於您在*之前*花時間進行安裝。



== 2022年9月6日（1.16版）



=== 能夠立即重新掃描儲存庫、以反映檔案中的變更

如果您需要立即重新掃描特定儲存庫、使變更反映在系統中、您可以選取儲存庫並重新掃描。這可讓您優先重新掃描特定資料、然後再處理其他資料。 https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#rescanning-data-for-an-existing-repository["請參閱如何重新掃描目錄"^]。



=== 在「資料調查」頁面中、新篩選「資料偵測掃描」狀態

「分析狀態」篩選器可讓您列出處於「資料感應」掃描特定階段的檔案。您可以選取一個選項來顯示*擱置第一次掃描*、*完成*正在掃描、*擱置重新掃描*或*失敗*要掃描的檔案清單。

https://docs.netapp.com/us-en/bluexp-classification/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["請參閱所有篩選器清單、以供您調查資料"^]。



=== 資料主體現在被視為掃描中「個人資料」的一部分

Data Sense現已將資料主體視為「法規遵循儀表板」中所顯示之「個人結果」的一部分。此外、在「調查」頁面中執行搜尋時、您可以選取「個人資料」下方的「資料主旨」、以僅檢視包含資料主旨的檔案。



=== 資料感測階層連結檔案現在被視為掃描中「類別」的一部分

Data Sense現在將階層連結檔案視為「符合性儀表板」中顯示的類別的一部分。將檔案從來源位置移至NFS共用時、會建立這些檔案Data Sense。 https://docs.netapp.com/us-en/bluexp-classification/task-managing-highlights.html#moving-source-files-to-an-nfs-share["深入瞭解如何建立階層連結檔案"^]。

此外、在「調查」頁面中執行搜尋時、您可以選取「類別」下的「資料感測Breadcrumbs」、以僅檢視「資料感測階層連結」檔案。



== 2022年8月7日（1.15版）



=== 來自紐西蘭的五種新型個人資料是由Data Sense所識別

Data Sense可識別及分類包含下列資料類型的檔案：

* 紐西蘭銀行帳戶號碼
* 紐西蘭駕駛證號碼
* 紐西蘭IRD編號（稅金ID）
* 紐西蘭NHI（國家健康指數）編號
* 紐西蘭護照號碼


link:reference-private-data-categories.html#types-of-personal-data["查看Data Sense可在您的資料中識別的所有個人資料類型"]。



=== 能夠新增階層連結檔案、以指出檔案移動的原因

當您使用「資料感應」功能將來源檔案移至NFS共用時、現在您可以將階層連結檔案保留在移動檔案的位置。階層連結檔案可協助使用者瞭解為何要將檔案從原始位置移出。對於每個移動的檔案、系統會在名為的來源位置建立階層連結檔案 `<filename>-breadcrumb-<date>.txt` 可顯示文件的移動位置和移動文件的用戶。 https://docs.netapp.com/us-en/bluexp-classification/task-managing-highlights.html#moving-source-files-to-an-nfs-share["深入瞭解"^]。



=== 您目錄中的個人資料和敏感個人資料會顯示在調查結果中

「資料調查」頁面現在會顯示您目錄（資料夾和共用）內的個人資料和敏感個人資料結果。 https://docs.netapp.com/us-en/bluexp-classification/task-controlling-private-data.html#viewing-files-that-contain-personal-data["請參閱此處的範例"^]。



=== 檢視已成功分類的磁碟區、儲存區等數量狀態

檢視Data Sense正在掃描的個別儲存庫（Volume、儲存區等）時、您現在可以看到「對應」的儲存庫數量、以及「分類」的儲存庫數量。在所有資料上執行完整AI識別時、分類所需時間會更長。 https://docs.netapp.com/us-en/bluexp-classification/task-managing-repo-scanning.html#viewing-the-scan-status-for-your-repositories["請參閱如何檢視此資訊"^]。



=== 現在、您可以在資料中新增Data Sense將識別的自訂模式

您可以使用兩種方法新增自訂的「個人資料」、以便Data Sense在未來的掃描中識別。如此一來、您就能完整瞭解所有組織檔案中潛在敏感資料所在的位置。

* 您可以從文字檔新增自訂關鍵字。
* 您可以使用規則運算式（regex）新增個人模式。


這些關鍵字和模式會新增至Data Sense已使用的現有預先定義模式、結果會顯示在「個人模式」區段下方。 https://docs.netapp.com/us-en/bluexp-classification/task-managing-data-fusion.html["深入瞭解"^]。
