---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, data sense' 
summary: 瞭解Cloud Data意義上的新功能。 
---
= Cloud Data Sense的新功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
瞭解Cloud Data意義上的新功能。



== 2023 年 4 月 3 日（版本 1.22 ）



=== 新的資料探索評估報告

「資料探索評估報告」會針對您所掃描的環境提供高層級分析、以強調系統的發現、並顯示關切領域和可能的補救步驟。本報告的目標是提高對資料治理疑慮、資料安全性曝露及資料集資料合規性缺口的認知度。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-governance-data.html#data-discovery-assessment-report["瞭解如何產生及使用資料探索評估報告"]。



=== 能夠在雲端的較小執行個體上部署 Data Sense

在 AWS 環境中從 BlueXP Connector 部署 Data Sense 時、現在您可以從兩種較預設執行個體可用的執行個體類型來選擇。如果您掃描的是小型環境、這有助於節省雲端成本。不過、使用較小的執行個體時會有一些限制。 https://docs.netapp.com/us-en/cloud-manager-data-sense/concept-cloud-compliance.html#using-a-smaller-instance-type["請參閱可用的執行個體類型和限制"]。



=== 獨立指令碼現在可供測試、您的 Linux 系統是否符合安裝 Data Sense 的資格

如果您想驗證 Linux 系統是否符合所有先決條件、而不需執行 Data Sense 安裝、您可以下載一個獨立的指令碼、只測試先決條件。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-test-linux-system.html["瞭解如何檢查您的 Linux 主機是否已準備好安裝 Data Sense"]。



== 2023年3月7日（版本1.21）



=== 新功能可從Data Sense UI新增您自己的自訂類別

Data Sense現在可讓您新增自己的自訂類別、讓Data Sense能夠識別符合這些類別的檔案。資料感測有許多 https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-private-data-categories.html#types-of-categories["預先定義的類別"]因此，此功能可讓您新增自訂類別，以識別在資料中找到組織專屬的資訊。

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-data-fusion.html#add-custom-categories["深入瞭解"^]。



=== 現在您可以從Data Sense UI新增自訂關鍵字

Data Sense能夠新增自訂關鍵字、讓Data Sense在未來一段時間內能識別這些關鍵字。不過、您需要登入Data Sense Linux主機、然後使用命令列介面新增關鍵字。在此版本中、新增自訂關鍵字的功能是在Data Sense UI中、因此很容易新增及編輯這些關鍵字。

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-data-fusion.html#add-custom-keywords-from-a-list-of-words["深入瞭解如何從Data Sense UI新增自訂關鍵字"^]。



=== 在「上次存取時間」變更時、能夠擁有Data Sense * Not *掃描檔案

根據預設、如果Data Sense沒有足夠的「寫入」權限、系統就不會掃描磁碟區中的檔案、因為Data Sense無法將「上次存取時間」還原為原始時間戳記。不過、如果您不在意上次存取時間是否重設為檔案中的原始時間、您可以在「組態」頁面中覆寫此行為、讓「Data Sense」（資料感測）不論權限為何、都能掃描磁碟區。

結合此功能、新增名為「掃描分析事件」的篩選器、讓您檢視未分類的檔案、因為「資料感應」無法回復上次存取時間、或是資料感應無法回復上次存取時間的檔案。

https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-collected-metadata.html#last-access-time-timestamp["深入瞭解「上次存取時間時間戳記」和Data Sense所需權限"]。



=== Data Sense可識別三種新類型的個人資料

Data Sense可識別及分類包含下列資料類型的檔案：

* 波札那身分證（Omang）號碼
* 波札那護照號碼
* 新加坡國家註冊身分證（NRIC）


https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-private-data-categories.html#types-of-personal-data["查看Data Sense可在您的資料中識別的所有個人資料類型"]。



=== 目錄的更新功能

* 資料調查報告的「輕度CSV報告」選項現在包含來自目錄的資訊。
* 「上次存取」時間篩選器現在會顯示檔案和目錄的上次存取時間。




=== 安裝增強功能

* Data Sense可安裝在執行CentOS Stream 8的Linux主機上。
* 不具備網際網路存取（黑點）的站台資料感知安裝程式現在會執行預先檢查、以確保您的系統和網路需求已就緒、可順利安裝。
* 安裝稽核記錄檔現在會儲存、並寫入 `/ops/netapp/install_logs`。




== 2023年2月5日（1.20版）



=== 能夠將原則型通知電子郵件傳送至任何電子郵件地址

在舊版的Cloud Data Sense中、當某些重要原則傳回結果時、您可以傳送電子郵件警示給帳戶中的BlueXP使用者。此功能可讓您取得通知、在您不在線上時保護資料。現在、您也可以將原則的電子郵件警示傳送給任何其他使用者（最多20個電子郵件地址）、而這些使用者不在您的BlueXP帳戶中。

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-using-policies.html#sending-email-alerts-when-non-compliant-data-is-found["深入瞭解如何根據原則結果傳送電子郵件警示"]。



=== 現在您可以從Data Sense UI新增個人模式

Data Sense能夠新增自訂的「個人資料」、讓Data Sense在未來一段時間的掃描中能夠識別這些資料。不過、您需要登入Data Sense Linux主機、然後使用命令列新增自訂模式。在此版本中、使用regex新增個人模式的功能位於Data Sense UI中、可讓您輕鬆新增及編輯這些自訂模式。

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-data-fusion.html#add-custom-personal-data-identifiers-using-a-regex["深入瞭解如何從Data Sense UI新增自訂模式"^]。



=== 能夠使用Data Sense搬移1500萬個檔案

過去、您可以讓Data Sense將最多100、000個來源檔案移至任何NFS共用區。現在您一次最多可以搬移1500萬個檔案。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#moving-source-files-to-an-nfs-share["深入瞭解如何使用Data Sense移動來源檔案"]。



=== 能夠查看有權存取SharePoint Online檔案的使用者人數

篩選器「具有存取權限的使用者人數」現在支援儲存在SharePoint Online儲存庫中的檔案。過去只支援CIFS共用上的檔案。請注意、目前不以Active Directory為基礎的SharePoint群組將不會計入此篩選器。



=== 新的「部分成功」狀態已新增至「行動狀態」面板

新的「部分成功」狀態表示「資料感知」動作已完成、部分項目失敗、部分項目成功、例如、您正在移動或刪除100個檔案時。此外、「已完成」狀態已重新命名為「成功」。過去、「已完成」狀態可能會列出成功及失敗的動作。現在「成功」狀態代表所有項目的所有行動都成功。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-view-compliance-actions.html["請參閱如何檢視「動作狀態」面板"]。



== 2023年1月9日（1.19版）



=== 能夠檢視含有敏感資料且過於許可的檔案圖表

「治理」儀表板新增了「敏感資料」和「廣泛權限」區域、提供內含敏感資料（包括敏感和敏感個人資料）且過於許可的檔案熱圖。這有助於您瞭解敏感資料的風險所在。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-governance-data.html#data-listed-by-sensitivity-and-wide-permissions["深入瞭解"]。



=== 「資料調查」頁面提供三種新篩選條件

我們提供新的篩選條件、以精簡「資料調查」頁面中顯示的結果：

* 「有存取權的使用者人數」篩選器會顯示哪些檔案和資料夾已對特定數量的使用者開放。您可以選擇一個數字範圍來精簡結果、例如、查看51到100位使用者可以存取哪些檔案。
* 「建立時間」、「探索時間」、「上次修改時間」和「上次存取時間」篩選條件現在可讓您建立自訂日期範圍、而不只是選擇預先定義的天數範圍。例如、您可以在「過去10天」內尋找「建立時間」為「6個月以上」或「上次修改日期」的檔案。
* 「檔案路徑」篩選現在可讓您指定要從篩選查詢結果中排除的路徑。如果您輸入同時包含和排除特定資料的路徑、Data Sense會先尋找包含路徑中的所有檔案、然後從排除路徑中移除檔案、然後顯示結果。


https://docs.netapp.com/us-en/cloud-manager-data-sense/task-investigate-data.html#filtering-data-in-the-data-investigation-page["請參閱所有篩選器清單、以供您調查資料"]。



=== Data Sense可識別日本的個人號碼

Data Sense可識別及分類含有日文個人號碼（也稱為「My Number（我的號碼）」）的檔案。這包括「個人」和「公司我的號碼」。 https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-private-data-categories.html#types-of-personal-data["查看Data Sense可在您的資料中識別的所有個人資料類型"]。



== 2022年12月11日（版本1.18）



=== 內部部署安裝增強功能

內部部署Data Sense安裝新增下列增強功能：

* 在內部部署主機上開始安裝之前、現在會先檢查其他一些先決條件。這有助於確保主機系統100%準備好安裝Data Sense軟體：
+
** 測試上是否有足夠的空間 `/var/lib/docker`、 `/tmp`和 `/opt`
** 測試所有必要資料夾的相關權限


* 在「組態」頁面中、「工作環境」區段現在會顯示_工作環境ID_和_掃描器群組_名稱。如果您打算使用多個Data Sense主機來提供額外的處理能力來掃描資料來源、則必須知道工作環境ID。
* 此外、在「組態」頁面中、會有一個新區段顯示您已設定的掃描器群組、以及每個群組中的掃描器節點。


https://docs.netapp.com/us-en/cloud-manager-data-sense/task-deploy-compliance-onprem.html["深入瞭解如何在單一主機伺服器和多個主機上安裝Data Sense"]。



== 2022年11月13日（1.17版）



=== 支援掃描SharePoint內部部署帳戶

Data Sense現在可以掃描SharePoint Online帳戶和SharePoint內部部署帳戶（SharePoint Server）。如果您需要在自己的伺服器上安裝SharePoint、或是在無法存取網際網路的站台上安裝SharePoint、現在您可以讓Data Sense掃描這些帳戶中的使用者檔案。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-scanning-sharepoint.html#adding-a-sharepoint-on-premise-account["深入瞭解"^]。



=== 能夠重新掃描多個目錄（資料夾或共用）

現在、您可以立即重新掃描多個目錄（資料夾或共用）、使變更反映在系統中。這可讓您優先重新掃描特定資料、然後再處理其他資料。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-repo-scanning.html#rescanning-data-for-an-existing-repository["請參閱如何重新掃描目錄"^]。



=== 能夠新增額外的內部部署「掃描器」節點、以掃描特定的資料來源

如果您已在內部部署位置安裝Data Sense、而且發現掃描特定資料來源需要更多掃描處理能力、您可以新增更多「掃描」節點、並指派它們來掃描這些資料來源。您可以在安裝管理節點之後立即新增掃描儀節點、也可以稍後新增掃描儀節點。

如有必要、可將掃描器節點安裝在實體靠近您要掃描之資料來源的主機系統上。掃描儀節點越靠近資料、越好、因為掃描資料時會盡可能減少網路延遲。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-deploy-compliance-onprem.html#add-scanner-nodes-to-an-existing-deployment["瞭解如何安裝掃描器節點來掃描其他資料來源"^]。



=== 內部部署安裝程式現在會在開始安裝之前執行預先檢查

在Linux系統上安裝Data Sense時、安裝程式會先檢查系統是否符合所有必要的需求（CPU、RAM、容量、網路等）、然後再開始實際安裝。這有助於您在*之前*花時間進行安裝。



== 2022年9月6日（1.16版）



=== 能夠立即重新掃描儲存庫、以反映檔案中的變更

如果您需要立即重新掃描特定儲存庫、使變更反映在系統中、您可以選取儲存庫並重新掃描。這可讓您優先重新掃描特定資料、然後再處理其他資料。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-repo-scanning.html#rescanning-data-for-an-existing-repository["請參閱如何重新掃描目錄"^]。



=== 在「資料調查」頁面中、新篩選「資料偵測掃描」狀態

「分析狀態」篩選器可讓您列出處於「資料感應」掃描特定階段的檔案。您可以選取一個選項來顯示*擱置第一次掃描*、*完成*正在掃描、*擱置重新掃描*或*失敗*要掃描的檔案清單。

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["請參閱所有篩選器清單、以供您調查資料"^]。



=== 資料主體現在被視為掃描中「個人資料」的一部分

Data Sense現已將資料主體視為「法規遵循儀表板」中所顯示之「個人結果」的一部分。此外、在「調查」頁面中執行搜尋時、您可以選取「個人資料」下方的「資料主旨」、以僅檢視包含資料主旨的檔案。



=== 資料感測階層連結檔案現在被視為掃描中「類別」的一部分

Data Sense現在將階層連結檔案視為「符合性儀表板」中顯示的類別的一部分。將檔案從來源位置移至NFS共用時、會建立這些檔案Data Sense。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#moving-source-files-to-an-nfs-share["深入瞭解如何建立階層連結檔案"^]。

此外、在「調查」頁面中執行搜尋時、您可以選取「類別」下的「資料感測Breadcrumbs」、以僅檢視「資料感測階層連結」檔案。



== 2022年8月7日（1.15版）



=== 來自紐西蘭的五種新型個人資料是由Data Sense所識別

Data Sense可識別及分類包含下列資料類型的檔案：

* 紐西蘭銀行帳戶號碼
* 紐西蘭駕駛證號碼
* 紐西蘭IRD編號（稅金ID）
* 紐西蘭NHI（國家健康指數）編號
* 紐西蘭護照號碼


link:reference-private-data-categories.html#types-of-personal-data["查看Data Sense可在您的資料中識別的所有個人資料類型"]。



=== 能夠新增階層連結檔案、以指出檔案移動的原因

當您使用「資料感應」功能將來源檔案移至NFS共用時、現在您可以將階層連結檔案保留在移動檔案的位置。階層連結檔案可協助使用者瞭解為何要將檔案從原始位置移出。對於每個移動的檔案、系統會在來源位置建立一個名為「<fileName（檔案名稱）>-breadcrumbsum-<date（日期）>.txt'的階層連結檔案、以顯示檔案的移動位置和移動檔案的使用者。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#moving-source-files-to-an-nfs-share["深入瞭解"^]。



=== 您目錄中的個人資料和敏感個人資料會顯示在調查結果中

「資料調查」頁面現在會顯示您目錄（資料夾和共用）內的個人資料和敏感個人資料結果。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#viewing-files-that-contain-personal-data["請參閱此處的範例"^]。



=== 檢視已成功分類的磁碟區、儲存區等數量狀態

檢視Data Sense正在掃描的個別儲存庫（Volume、儲存區等）時、您現在可以看到「對應」的儲存庫數量、以及「分類」的儲存庫數量。在所有資料上執行完整AI識別時、分類所需時間會更長。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-repo-scanning.html#viewing-the-scan-status-for-your-repositories["請參閱如何檢視此資訊"^]。



=== 現在、您可以在資料中新增Data Sense將識別的自訂模式

您可以使用兩種方法新增自訂的「個人資料」、以便Data Sense在未來的掃描中識別。如此一來、您就能完整瞭解所有組織檔案中潛在敏感資料所在的位置。

* 您可以從文字檔新增自訂關鍵字。
* 您可以使用規則運算式（regex）新增個人模式。


這些關鍵字和模式會新增至Data Sense已使用的現有預先定義模式、結果會顯示在「個人模式」區段下方。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-data-fusion.html["深入瞭解"^]。



== 2022年7月6日（1.14版）



=== 現在您可以檢視擁有目錄存取權的使用者和群組

過去您可以檢視個別檔案所授予的開啟權限類型。現在您可以檢視所有存取目錄（資料夾和檔案共用）的使用者或群組清單、以及他們擁有的權限類型。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#viewing-permissions-for-files-and-directories["瞭解如何檢視可存取您資料夾和檔案共用的使用者和群組"]。



=== 您可以「暫停」掃描儲存庫、暫時停止掃描特定內容

暫停掃描表示「Data Sense」（資料感測）將不會在任何新增或變更磁碟區或儲存區的情況下執行未來掃描、但系統仍會提供所有目前的結果。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-repo-scanning.html#pausing-and-resuming-scanning-for-a-repository["瞭解如何暫停和繼續掃描"]。



=== Data Sense可識別來自其他三種狀態的美國駕駛證資料

Data Sense可識別及分類包含來自印第安納州、紐約州和德州的駕駛授權資料的檔案。 link:reference-private-data-categories.html#types-of-personal-data["查看Data Sense可在您的資料中識別的所有個人資料類型"]。



=== 原則現在會傳回符合搜尋條件的目錄

過去當您建立自訂原則時、結果會顯示符合搜尋條件的檔案。結果也會顯示符合查詢的目錄（資料夾和檔案共用）。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-org-private-data.html#creating-custom-policies["深入瞭解如何建立原則"]。



=== Data Sense現在一次最多可移動100、000個檔案

如果您打算使用Data Sense將檔案從掃描的資料來源移至NFS共用區、則檔案的最大數量已增加至100、000個檔案。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-managing-highlights.html#moving-source-files-to-an-nfs-share["瞭解如何使用Data Sense移動檔案"]。



== 2022年6月12日（1.13.1版）



=== 現在您可以從「資料調查」頁面下載結果、做為.Json報告

在「資料調查」頁面中篩選資料之後、除了將資料儲存至本機系統上的.CSV檔案之外、現在您還可以將資料另存為.Json檔案、以便匯出至NFS共用。確認Data合理擁有正確的匯出存取權限。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-generating-compliance-reports.html#data-investigation-report["請參閱如何從「資料調查」頁面建立報告"]。



=== 能夠從Data Sense UI解除安裝Data Sense

您可以解除安裝Data Sense、將軟體從主機中永久移除、如果是雲端部署、請刪除部署Data Sense的虛擬機器/執行個體。刪除執行個體會永久刪除所有已建立索引的資訊Data Sense已掃描。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-uninstall-data-sense.html["瞭解方法"]。



=== 稽核記錄功能現在可用來追蹤Data Sense所執行的行動記錄

稽核日誌會追蹤Data Sense對所有工作環境中的檔案所執行的管理活動、以及Data Sense正在掃描的資料來源。活動可以是使用者產生的（刪除檔案、建立原則等）或產生的原則（自動新增標籤至檔案、自動刪除檔案等）。

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-audit-data-sense-actions.html["如需稽核記錄的詳細資料、請參閱"]。



=== 在「Data Investigation」（資料調查）頁面中新增敏感識別碼的篩選器

「識別碼數量」篩選器可讓您列出具有特定數量敏感識別碼的檔案、包括個人資料和敏感個人資料。您可以選取1到10或1到1000等範圍、只檢視含有該敏感識別碼數目的檔案。

https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["請參閱所有篩選器清單、以供您調查資料"]。



=== 現在您可以編輯所建立的現有原則

如果您需要變更過去建立的自訂原則、現在您可以編輯原則、而非建立新原則。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-org-private-data.html#editing-policies["瞭解如何編輯原則"]。



== 2022年5月11日（1.12.1版）



=== 新增支援在Google雲端硬碟帳戶中掃描資料

現在您可以將Google雲端硬碟帳戶新增至Data Sense、以便從這些Google雲端硬碟帳戶掃描文件和檔案。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-scanning-google-drive.html["瞭解如何掃描Google雲端硬碟帳戶"]。

Data Sense可從Google Docs套件（文件、工作表和投影片）中識別下列Google檔案類型中的個人識別資訊（PII）、以及 https://docs.netapp.com/us-en/cloud-manager-data-sense/reference-private-data-categories.html#types-of-files["現有檔案類型"]。



=== 目錄層級檢視已新增至「資料調查」頁面

除了檢視及篩選所有檔案和資料庫的資料、現在您還可以根據資料調查頁面中資料夾和共用區內的所有資料來檢視及篩選資料。系統會為已掃描的CIFS和NFS共用、以及OneDrive、SharePoint和Google Drive資料夾建立目錄索引。現在您可以在目錄層級檢視權限並管理資料。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["瞭解如何選取掃描資料的「目錄」檢視"]。



=== 展開群組以顯示具有存取檔案權限的使用者/成員

身為Data Sense權限功能的一部分、您現在可以檢視擁有檔案存取權的使用者和群組清單。每個群組都可展開以顯示群組中的使用者清單。 https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#viewing-permissions-for-files["瞭解如何檢視具有檔案讀取和/或寫入權限的使用者和群組"]。



=== 「資料調查」頁面新增兩個篩選條件

* 「目錄類型」篩選器可讓您精簡資料、只查看資料夾或共用區。結果將顯示在新的*目錄*索引標籤中。
* 「使用者/群組權限」篩選器可讓您列出特定使用者或群組具有讀取和/或寫入權限的檔案、資料夾和共用。您可以選取多個使用者和/或群組名稱、或輸入部分名稱。


https://docs.netapp.com/us-en/cloud-manager-data-sense/task-controlling-private-data.html#filtering-data-in-the-data-investigation-page["請參閱所有篩選器清單、以供您調查資料"]。



== 2022年4月5日（版本1.11.1）



=== Data Sense可識別四種新類型的澳洲個人資料

Data Sense可識別及分類包含澳洲（TFN）（稅務檔案編號）、澳洲駕駛證編號、澳洲醫療保險編號及澳洲護照編號的檔案。 link:reference-private-data-categories.html#types-of-personal-data["查看Data Sense可在您的資料中識別的所有個人資料類型"]。



=== 現在全域Active Directory伺服器可以是LDAP伺服器

除了先前支援的DNS伺服器之外、您與Data Sense整合的全域Active Directory伺服器現在也可以是LDAP伺服器。 link:task-add-active-directory-datasense.html["如需詳細資料、請前往此處"]。



== 2022年3月15日（版本1.10.0）



=== 新篩選器、顯示特定使用者或群組擁有讀取或寫入權限的檔案

已新增名為「使用者/群組權限」的篩選器、以便列出特定使用者或群組具有讀取和/或寫入權限的檔案。您可以選取一或多個使用者和/或群組名稱、或輸入部分名稱。此功能適用於Cloud Volumes ONTAP 下列系統上的Volume：功能：功能包括：功能性、內部ONTAP 版本、功能性、Azure NetApp Files 功能性、功能性、功能性ONTAP 、功能性、功能性、功能性、功能性、功能性、功能性、功能性、可在



=== Data Sense可決定SharePoint和OneDrive帳戶中檔案的權限

Data Sense現在可以讀取OneDrive帳戶和SharePoint帳戶中掃描檔案的權限。此資訊會顯示在檔案的「調查」窗格詳細資料中、以及「治理儀表板」的「開放權限」區域中。



=== Data Sense可識別兩種其他類型的個人資料

* 法文INSEE：INSEE程式碼是法國國家統計與經濟研究所（INSEE）用來識別各種實體的數值代碼。
* 密碼：此資訊是使用鄰近驗證來識別、方法是在英數字元字串旁尋找「password」一詞的排列。找到的項目數量將列在「法規遵循儀表板」的「個人結果」下方。您可以使用「篩選*個人資料>密碼*」在「調查」窗格中搜尋包含密碼的檔案。




=== 支援在黑暗站台部署OneDrive和SharePoint資料時掃描

當您在內部部署網站的主機上部署Cloud Data Sense、但該網站無法存取網際網路時、現在您可以從OneDrive帳戶或SharePoint帳戶掃描本機資料。 link:task-deploy-compliance-dark-site.html#sharepoint-and-onedrive-special-requirements["您必須允許存取下列端點。"]



=== 此版本已停止使用Cloud Data Sense掃描雲端備份檔案的試用版功能



== 2022年2月9日



=== 新增掃描Microsoft SharePoint線上帳戶的支援

現在您可以將SharePoint線上帳戶新增至Data Sense、以便從SharePoint網站掃描文件和檔案。 link:task-scanning-sharepoint.html["瞭解如何掃描SharePoint帳戶"]。



=== Data Sense可將檔案從資料來源複製到目標位置、並同步處理這些檔案

如果您正在移轉資料、而且想要追蹤檔案的任何最後變更、這項功能就很有幫助。此動作使用 https://docs.netapp.com/us-en/cloud-manager-sync/concept-cloud-sync.html["NetApp Cloud Sync"^] 將資料從來源複製及同步至目標的功能。

link:task-managing-highlights.html#copying-and-synchronizing-source-files-to-a-target-system["瞭解如何複製及同步檔案"]。



=== 為DSAR報告提供新的語言支援

目前支援使用德文和西班牙文搜尋資料主體名稱、以建立資料主體存取要求（DSAR）報告。本報告旨在協助貴組織遵守GDPR或類似的資料隱私權法律。



=== Data Sense可識別三種其他類型的個人資料

Data Sense現在可以在檔案中找到法文社會安全號碼、法文ID和法文驅動程式授權號碼。 link:reference-private-data-categories.html#types-of-personal-data["請參閱「Data Sense」在掃描中識別的所有個人資料類型清單"]。



=== 安全性群組連接埠已變更、以便與連接器進行Data Sense通訊

Cloud Manager Connector的安全性群組將使用連接埠443、而非連接埠80、用於往返Data Sense執行個體的傳入和傳出流量、以提高安全性。這兩個連接埠目前仍為開啟狀態、因此您不會看到任何問題、但您應該更新任何舊版連接器部署中的安全性群組、因為連接埠80將在未來的版本中被淘汰。
