= 版本 1.40
:allow-uri-read: 




=== 版本 1.40

此 BlueXP  分類版本包含下列更新。

.支援 RHEL 9.5
除了先前支援的版本之外、此版本還支援 Red Hat Enterprise Linux v9.5 。這適用於任何手動內部部署的 BlueXP  分類安裝、包括暗點部署。

下列作業系統需要使用 Podman Container 引擎，而且需要 BlueXP  分類 1.30 版或更新版本： Red Hat Enterprise Linux 8.8 ， 8.10 ， 9.0 ， 9.1 ， 9.2 ， 9.3 ， 9.4 和 9.5 版。

.排定掃描的優先順序
掃描組態時，您可以優先處理最重要的掃描，以便在進行其他掃描之前完成掃描。當您有許多工作環境，且想要確保一開始就成功完成高優先順序掃描時，此功能將有助於您。

掃描有兩種類型：

* * 僅對應掃描 * 僅提供資料的高層級總覽。您可以很快在資料來源上完成對應、因為它不會存取檔案來查看內部資料。
* * 地圖和分類 * 掃描可提供資料的深度掃描。


您可能會受益於使用純對應掃描來快速掃描資料，以識別需要更多研究的資料來源，然後再啟用地圖功能，並僅在這些必要的資料來源或磁碟區上分類掃描。

優先順序僅指派給僅對應掃描，而非對應和分類掃描。

依預設，優先順序設為 1 ，您可以將其變更為 1 到 10 之間的任何數字。數字越小，優先順序越高。如果您未設定優先級，則掃描的優先級為 5。

若要變更優先順序，請執行下列步驟：

. 從 BlueXP  分類功能表中，選取 * 組態 * 。
. 選取您要排定優先順序的資源。
. 從 Actions ... （操作 ... ）選項中，選擇 * 優先掃描 * 。


.重試掃描
在此版本中，您可以重試失敗的掃描。當掃描因為暫時性問題（例如網路中斷）而失敗時，此功能非常實用。您無需重新設定即可重試掃描。

若要重試掃描，請執行下列步驟：

. 從 BlueXP  分類功能表中，選取 * 組態 * 。
. 執行下列其中一項：
+
** 若要重試所有失敗的掃描，請選取 * 重試所有掃描 * 。
** 若要重試特定掃描，請選取資源，然後從「動作 ... 」選項中選取「 * 重試掃描 * 」。




掃描會以與原始掃描相同的組態重試。如果掃描再次失敗，您可以視需要重試多次。
