= 版本 1.40
:allow-uri-read: 




=== 版本 1.40

此 BlueXP  分類版本包含下列更新。

.支援 RHEL 9.5
除了先前支援的版本之外、此版本還支援 Red Hat Enterprise Linux v9.5 。這適用於任何手動內部部署的 BlueXP  分類安裝、包括暗點部署。

下列作業系統需要使用 Podman Container 引擎，而且需要 BlueXP  分類 1.30 版或更新版本： Red Hat Enterprise Linux 8.8 ， 8.10 ， 9.0 ， 9.1 ， 9.2 ， 9.3 ， 9.4 和 9.5 版。

.排定僅對應掃描的優先順序
執行僅對應掃描時，您可以優先處理最重要的掃描。當您有許多工作環境，且想要確保先完成高優先順序掃描時，此功能會有所幫助。

依預設，掃描會根據其啟動順序排入佇列。有了優先處理掃描的能力，您就可以將掃描移到佇列的前方。可以優先處理多個掃描。優先順序是以先出的順序指定，也就是您優先處理的第一次掃描會移到佇列前方；您優先處理的第二次掃描會成為佇列中的第二次掃描，依此類推。

優先順序是一次性授予。自動重新掃描對應資料會依預設順序進行。

優先順序僅限於link:concept-cloud-compliance.html["僅對應掃描"]；不適用於地圖和分類掃描。

如需更多資訊、請參閱 link:task-managing-repo-scanning.html#prioritize-scans["排定掃描的優先順序"]。

.重試所有掃描
BlueXP  分類支援批次重試所有失敗掃描的功能。

您可以使用「 ** 全部重試」功能，在批次作業中重新嘗試掃描。如果分類掃描因網路中斷等暫時性問題而失敗，您可以使用單一按鈕同時重試所有掃描，而無需個別重試。掃描可視需要重試多次。

若要重試所有掃描：

. 從 BlueXP  分類功能表中，選取 * 組態 * 。
. 若要重試所有失敗的掃描，請選取 * 重試所有掃描 * 。


.改善分類模型準確度
的機器學習模型準確度link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-sensitive-personal-datapredefined-categories["預先定義的類別"]已提升 11% 。
